### ISSUE TITLE
month label is not updated on locale change

### ISSUE THREAD

**Issue by nul0m** [arca-computing/MultipleDatePicker#100]
When I change locale using `moment.locale('fr-FR')` only weekday labels are changed, but the month label stays the same. It changes only after a page refresh.
![image](https://cloud.githubusercontent.com/assets/6223985/26215072/2982cdc6-3bff-11e7-99b1-52cbf3601347.png)

**Comment by mgohin** [comment]
Ho right ! Gonna fix that tomorrow ;)

**Comment by mgohin** [comment]
Fixed in [2.1.2](https://github.com/arca-computing/MultipleDatePicker/releases/tag/2.1.2) ;)

**Comment by nul0m** [comment]
@mgohin great job, thanks!
