### ISSUE TITLE
selected/deselected handler

### ISSUE THREAD

**Issue by dion1512** [arca-computing/MultipleDatePicker#102]
Can anyone advise how I can listen for whether a date is selected or deselected?

`var app = angular.module('demoApp', ['multipleDatePicker']);
app.controller('demoController', ['$scope', function ($scope) {
$scope.today = moment();
$scope.checkSelection = function(event, date) {

if day is selected do this
else
if day is deselected do this
}
}]);`

Thanks

**Comment by mgohin** [comment]
Hi,

everything is in the doc : http://arca-computing.github.io/MultipleDatePicker/#dayclickdayhover

**Comment by dion1512** [comment]
Thanks for your reply
That is listening for both click/unclick of a date in the same function

I am wondering how to distinguish between the two?

**Comment by mgohin** [comment]
if(day.mdp.selected){...}

The `day-click` callback is for checking and preventing event to happen if needed. All selected dates are in your `ng-model` array :)

**Comment by dion1512** [comment]
That works backwards to what I was expecting but it works

if(date.mdp.selected){ alert("unclick"); }
else { alert("click " + date.date.format('YYYY-MM-DD')); }


Thank you :)
