### ISSUE TITLE
selectedDays over several months

### ISSUE THREAD

**Issue by dion1512** [arca-computing/MultipleDatePicker#103]
Hi again

Could you please advise how I am able to select dates over several months?

As per documentation, I can select days on a single month using the following code:

`$scope.selectedDays = [moment().date(13), moment().date(15), moment().date(17)];`

How could I go about having preselected dates in another month?

Many thanks

**Comment by mgohin** [comment]
Hi,

you just have to change month :

    $scope.selectedDays = [moment.month(2).date(13), ...]

Didn't tested it but you can check the [momenJs Doc](https://momentjs.com/docs/)
Be aware of the warning here : https://momentjs.com/docs/#/get-set/date/
