### ISSUE TITLE
Select a day by code

### ISSUE THREAD

**Issue by chy89310** [arca-computing/MultipleDatePicker#105]
Hi there. I set the $scope variable as a global variable as follow:
```
var scope;
var app = angular.module('demoApp', ['multipleDatePicker']);
app.controller('demoController', ['$scope', function ($scope) {
    scope = $scope;
}
```
And I select the date by program as follow:
```
scope.myArrayOfDates=[moment()];
```
However, the datepicker want update the selected date with red background layout until I hover any date in the datepicker.
Do I miss something or there is any better way to select dates by program? Thank you.

**Comment by mgohin** [comment]
Hi,

I don't get everything, why do you copy the scope variable ?

Can you provide more code of your controller please ?

**Comment by chy89310** [comment]
Because I want to access the scope outside the controller block. I have other action outside the controller block to decide which dates should be selected. And I want to select the dates by program.
By the way, myArrayOfDates is a ng-model for the multiple date picker refer from the demo code.

**Comment by mgohin** [comment]
You can init the `myArrayOfDates` once and pass it to the directive, then if you want to change the date you have to change the array, not redefine it with an `=`, there is a watch on it but it's not triggered when you redefine it, it's an angular thing.

So, just do once `scope.myArrayOfDates=[moment()]` then to select only one date do
```javascript
scope.myArrayOfDates.splice(0, scope.myArrayOfDates.length);
scope.myArrayOfDates.push(moment());
```

**Comment by chy89310** [comment]
Thank you for you reply, however, it still don't work.
Please refer to my app.js:
```
var scope;
function myCallback() {
    scope.myArrayOfDates.push(moment());
}
var app = angular.module('demoApp', ['multipleDatePicker']);
app.controller('demoController', ['$scope', function ($scope) {
        scope = $scope;
        $scope.myArrayOfDates = [];
}]);
```
And front end is something like:
```
<html>
    <body>
        <multiple-date-picker ng-model="myArrayOfDates" sunday-first-day="true" disable-days-before="today"></multiple-date-picker>
    </body>
</html>
```
When I call myCallback() function, the layout will not update until I hover on the date picker.

**Comment by mgohin** [comment]
I don't have much time right now, can you provide a https://jsfiddle.net/ please to test it online ?

**Comment by chy89310** [comment]
https://jsfiddle.net/o4gq4hgm/5/

**Comment by chy89310** [comment]
I already resolve it! I update the myArrayOfDates using a function inside the controller will works. And I trigger the function using a ng-click action of the button. In that case I no need to cop the $scope variables.
Demo can refer from: https://jsfiddle.net/o4gq4hgm/7/
Btw, thanks for your patient reply, I'm new to angular, not so familiar with the ng stuff.

**Comment by mgohin** [comment]
Glad you found 👏
