### ISSUE TITLE
Adding an ID to a date object and persisting it when day is pushed to ng-model

### ISSUE THREAD

**Issue by gerardvcruz** [arca-computing/MultipleDatePicker#110]
Hello!

I'm trying to add a unique ID to every date on the calendar. I'm currently doing something like this:

```javascript
var date = moment(session.start)
date.id = session.id
return date
```

The dates are populating my `availableDates` array are the dates that you can select on the calendar. 

Unfortunately, after selecting a date on the calendar, the date that is pushed in my ng-model loses the ID that I assigned; it becomes a standard `moment()` object. Is there anyway this can be done?

Thanks

**Comment by mgohin** [comment]
If you are able to assign an ID to a date when building your `availableDates` you should be able to do it in `dayClick` function ?
Like :

    $scope.dayClick(event, day) {
        var id = getIdForDate(day.date);
        day.date.id = id;
    }

(not tested)

    <multiple-date-picker day-click='dayClick' ... />

http://arca-computing.github.io/MultipleDatePicker/#dayclickdayhover

**Comment by gerardvcruz** [comment]
I'm assigning the ID when building `availableSessions` (similar to `availableDates`)

```javascript
$scope.availableSessions = schedule.sessions.map(function(session) {
  if (session.slotsAvailable > 0 && moment(session.start).isAfter(moment())) {
    var date = moment(session.start)
    date.id = session.id

    return date
  }
})
```

I don't assign the ID in the day click. When I day click, the ID I assigned to the `moment()` object is gone. I would like the ID to persist when I `dayClick()` without having to reassign it.

**Comment by mgohin** [comment]
`availableSessions` is assigned to what in the directive, `ngModel` ?

**Comment by gerardvcruz** [comment]
Yes :)

**Comment by mgohin** [comment]
I'm sorry to say that the lib can't do it the way you want, but you can find the date in the dayClick, something like :

```javascript
var sessions = $scope.availableSessions.slice(); //copy your array
$scope.dayClick = function(event, day) {
    for(session of sessions){
        if(session.isSame(day.date, 'day') {
            day.date.id = session.id;
        }
    }
}
```

**Comment by gerardvcruz** [comment]
Yeah, that's what I was thinking too. I was just hoping I wouldn't have to do date comparison. 😢

Thank you for your help!
