### ISSUE TITLE
enable-select-month="true" is not working

### ISSUE THREAD

**Issue by AlphaNerd** [arca-computing/MultipleDatePicker#113]
Any reason why this wouldn't work? 
<multiple-date-picker ng-model="displayDates" change-year-past="5" enable-select-month="true"></multiple-date-picker>

<multiple-date-picker ng-model="displayDates" change-year-past="5" enable-select-month="true"></multiple-date-picker>

<img width="601" alt="screen shot 2018-02-16 at 7 37 33 am" src="https://user-images.githubusercontent.com/3393645/36306475-3fddd216-12ee-11e8-8b4a-063071fc6df3.png">

**Comment by AlphaNerd** [comment]
<multiple-date-picker ng-model="displayDates" change-year-past="5" enable-select-month="true"></multiple-date-picker>

**Comment by mgohin** [comment]
Which version are you using ?
Can you provide some code ? (html/js)
