### ISSUE TITLE
Exceptions while adding basic datepicker

### ISSUE THREAD

**Issue by noamweinman** [arca-computing/MultipleDatePicker#116]
Hey,
Don't know if this is the proper place, but I'll try.
Iv'e tried to add the date picker as told on the formal site, AKA:
1. added the 2 files to include (multipleDatePicker.css, multipleDatePicker.min.js)
2. added the module to angular app (angular.module('myApp', ['multipleDatePicker']);)
3. and the directive itself to the html ( <multiple-date-picker></multiple-date-picker>)

BUT, I got the following errors, what I'm missing?

![image](https://user-images.githubusercontent.com/13788127/38166982-0a34f602-3536-11e8-847e-9f7fff4182c1.png)
![image](https://user-images.githubusercontent.com/13788127/38166984-19e2b904-3536-11e8-8732-ff3f82141955.png)

Thanks for any help!

**Comment by mgohin** [comment]
Hi,

did you add MomentJS in your project ?
http://arca-computing.github.io/MultipleDatePicker/#momentjs

**Comment by noamweinman** [comment]
well, that's fixed the issue! thanks!!
