### ISSUE TITLE
week-days-off from js

### ISSUE THREAD

**Issue by lolovassia** [arca-computing/MultipleDatePicker#117]
Hi, I want to select week days off from my code in JS.
Can I do it?

Thanks

**Comment by mgohin** [comment]
Hi,

Yes you can, just add those days in ng-model ?

**Comment by lolovassia** [comment]
But I dont want to select day by day, I want to disable the days according to the number (for example: saturdays and sundays with [6, 0])

**`<multiple-date-picker day-click="checkSelection" sunday-first-day="true" week-days-off="[0,6]" id="fechaVisita" ng-model="fechaVisita"></multiple-date-picker>`**

This is okay. But my days disable are dynamic. And I need doing from code in js

**Comment by mgohin** [comment]
I don't get it, you want to select disabled days ?!

**Comment by lolovassia** [comment]
No, I want to disable the days of the week dynamically from my code in JS.
Because sometimes it will be enabled from Monday to Friday, and sometimes from Monday to Saturday.

**Comment by mgohin** [comment]
just pass a variable instead of just an anonymous array :

```javascript
var computeDaysOff = function (month) {
    $scope.daysOff = ...;//computation
}

$scope.monthChanged = function(newMonth, oldMonth){
    computeDaysOff(newMonth);
};
```

```html
<multiple-date-picker month-changed="monthChanged" week-days-off="daysOff"/>
```

This will compute new days off everytime you change the month. Didn't test it, I wrote it here

**Comment by lolovassia** [comment]
THANKKKSS!!!!! I just had to declare a variable in week-days-off
I solved:
`<multiple-date-picker day-click="checkSelection" sunday-first-day="true" **week-days-off="daysOff"** id="fechaVisita" ng-model="fechaVisita"></multiple-date-picker>`

**Comment by mgohin** [comment]
;)
