### ISSUE TITLE
"month" change does not affect selected month.

### ISSUE THREAD

**Issue by nooneexpectthis** [arca-computing/MultipleDatePicker#119]
Hello.
Is it possible to change current month by code?
On init it works. But later on, when I change variable binded with [month] It does not affect calendar.
Code:
HTML:
      <multiple-date-picker *ngIf="isDataAvailable"
                            [showDaysOfSurroundingMonths]="false"
                            [dayClick]="oneDaySelectionOnly"
                            [(highlightDays)]="highlightDays"
                            [(month)]="month"
                            [disallowBackPastMonths]="true"
                            [disableDaysBefore]="currentDate"
                            [(ngModel)]="initialCount">
      </multiple-date-picker>
JS:
  month: Moment = moment(); //curent

  goToFirstAvailableDate()
  {
    this.month.set('month', 5);
  }

Greetings

**Comment by mgohin** [comment]
$scope.month = $scope.month.month(5);

try ;)

**Comment by nooneexpectthis** [comment]
![image](https://user-images.githubusercontent.com/38134623/41421257-ad97777a-6ff6-11e8-955f-055d35a2b76e.png)
Moment variable binded with MDP [month] is changing, but does not affect calendar. Maybe any workaround?

**Comment by mgohin** [comment]
--> http://arca-computing.github.io/MultipleDatePicker/#month

**Comment by nooneexpectthis** [comment]
It works only when setting month='' on init. Unfortunately very other case does not affect calendar.

**Comment by mgohin** [comment]
It's because of the way Angular checks updates

**Comment by nooneexpectthis** [comment]
Is there any way to force mdp to reinit or check again for month value?

**Comment by mgohin** [comment]
Sorry I though it was ok, miss reading.
It should be working, there is a watch on it. 
I guess something is messing with it, do you use any framework, live reload ?

**Comment by nooneexpectthis** [comment]
Angular 5.0.2 + NgbActiveModal

**Comment by mgohin** [comment]
Angular 5 ? LoL this is an angular 1 directive 🤣

**Comment by mgohin** [comment]
Sorry about the confusion, I added some info in the project description and readme :/

**Comment by nooneexpectthis** [comment]
Oh, I thought u rewrited package to work under angular 2+ :)

**Comment by mgohin** [comment]
Someone wanted to do it but looks like he stopped :/
