### ISSUE TITLE
How skip highlights day

### ISSUE THREAD

**Issue by stefanekaresta** [arca-computing/MultipleDatePicker#120]
Hi, can u fix this? I have some problem.
I have automatically added 3 days at the dayclick event, can I skip the days that have been highlighted? for example highlights on the 16th and 17th and I automatically added from the 15th for the next 3 days.
the final result I want to get is the 15th 18th and 19th.

Thanks..

**Comment by mgohin** [comment]
When you highlight days you know those days somewhere in your code.
When you had the 3 days you just have to compare those days to the highlight days, and skip any you want.
I think it's a problem in your algorithm, not the lib ;)

**Comment by stefanekaresta** [comment]
oke. thanks for your answer. i ll fix my algorithm..

Thanks

**Comment by stefanekaresta** [comment]
Thanks for your answer. I will fix my algorithm.

Thanks
