### ISSUE TITLE
Help needed..how do i push dates in new array?

### ISSUE THREAD

**Issue by shriramsalunkheprisanas** [arca-computing/MultipleDatePicker#121]
i want to extract dates from myArrayOfDates and push them into my new array (newDates) when i click on dates and push them into my array dates are getting repeted..
here's my code..

<multiple-date-picker ng-model="myArrayOfDates" change-year-past="5" change-year-future="10" enable-select-month="true" ng-click="BlackoutDay()"></multiple-date-picker>

$scope.newDates=[];
    $scope.myArrayOfDates = [moment().date(4), moment().date(5), moment().date(8)];
    $scope.BlackoutDays=[];
    $scope.$watch('myArrayOfDates', function(newValue, oldValue)
    {
        if(newValue)
        {
            console.log($scope.myArrayOfDates);
        }
    }, true);
     $scope.BlackoutDay=function()
    {  
        angular.forEach($scope.myArrayOfDates, function(key,value)
         {
                $scope.BlackoutDays=moment(key._d).format('YYYY-MM-DD');
          console.log($scope.BlackoutDays);
           var date = moment(key._d).format('YYYY-MM-DD');
            $scope.supplier.supplier_blackout_day=[{
                      "day":moment(key._d).format('YYYY-MM-DD')
                    }]
             console.log($scope.supplier.supplier_blackout_day);
        });
       
    }

**Comment by shriramsalunkheprisanas** [comment]
<multiple-date-picker ng-model="myArrayOfDates" change-year-past="5" change-year-future="10" enable-select-month="true" ng-click="BlackoutDay()"></multiple-date-picker>

**Comment by mgohin** [comment]
Sorry I don't get what you want. First can you format your request with code block ?

**Comment by shriramsalunkheprisanas** [comment]
okay,
Here's my html:
<multiple-date-picker ng-model="myArrayOfDates" change-year-past="5" change-year-future="10" enable-select-month="true" ng-click="BlackoutDay()">
</multiple-date-picker>

when I click on date : I receive array of moment object as follows:

0: n {_isAMomentObject: true, _isUTC: false, _locale: r, _d: Tue Sep 04 2018 13:52:49 GMT+0530 (India Standard Time)}
1: n {_isAMomentObject: true, _isUTC: false, _locale: r, _d: Wed Sep 05 2018 13:52:49 GMT+0530 (India Standard Time)}
2: n {_isAMomentObject: true, _isUTC: false, _locale: r, _d: Sat Sep 08 2018 13:52:49 GMT+0530 (India Standard Time)}
length: 3
__proto__: Array(0)

I want to extract date In YYYY-MM-DD format.

and once i get date in YYYY-MM-DD format i want to push that date to my new array in following format
      supplier_blackout_day:
       {
              "day": date
       }

**Comment by shriramsalunkheprisanas** [comment]
$scope.BlackoutDay=function(){
        angular.forEach($scope.myArrayOfDates,function(value,key){
           console.log(value._d);
            $scope.supplier.supplier_blackout_day.push({
                "day":moment(value._d).format('YYYY-MM-DD')
            });
        })
        console.log($scope.supplier.supplier_blackout_day);
    }

**Comment by shriramsalunkheprisanas** [comment]
How do I extract date from myArrayOfDates? and push to array in following format
{
   "day":"date"
}

**Comment by shriramsalunkheprisanas** [comment]
if  i push dates in array dates are getting repeated :

(3) [{…}, {…}, {…}]
0: {day: "2018-09-04"}
1: {day: "2018-09-05"}
2: {day: "2018-09-04"}
length: 3
__proto__: Array(0)

**Comment by mgohin** [comment]
Come on, put some efforts, I don't want your whole code, I want you to format it correctly here, because it's not readable --> https://guides.github.com/features/mastering-markdown/

**Comment by shriramsalunkheprisanas** [comment]
my problem is simple,I just want to get dates in YYYY-MM-DD format from myArrayOfDates.
so,
my question is how do i read  _d  from myArrayOfDates.
thanks.
