### ISSUE TITLE
How can I display (with text) the dates that are selected?

### ISSUE THREAD

**Issue by marinarose92** [arca-computing/MultipleDatePicker#122]
Hello,

I am looking for a way to display the dates that are selected. For example, if I click on March 15, an area at the bottom of the screen will display: "2018-03-13" or something like that.

I see that dayClick will probably be somehow involved in this, and I feel like the right-click callback feature is a little bit of what I want to do (since it does display the selected date). I'm not sure where to go from here, though.

```/*Check if the date is selected*/

scope.isSelected = function (day) {

return scope.ngModel.some(function (d) {

return day.date.isSame(d, 'day');

                        });

                    };`


After checking for which is selected, how to display?

Thank you!

**Comment by mgohin** [comment]
Hi,

`dayclick` is useful to prevent (un)selection to happen if you need to.
What you need is simple to add a dom element with a `ng-repeat` on your `ng-model`.
Let's say you start with : 

    //JS
    $scope.myArrayOfDates = [];

    //HTML
    <div>
        <span ng-repeat="date in myArrayOfDates">{{date | date:'dd-MM-yyyy'}}</span>
    </div>

You could also listen your `ng-model` variable, as explained here : http://arca-computing.github.io/MultipleDatePicker/#ngmodel but I think the first solution is best.

Let me know if it's what you want.

**Comment by marinarose92** [comment]
This is great, thank you! The only thing that's occurring now is the expression is showing the date as: Tue Jun 12 2018 08:47:20 GMT-0400 but shouldn't it be dd-MM-yyyy?

**Comment by mgohin** [comment]
Because it's a moment object, try something like

    <span ng-repeat="date in myArrayOfDates">{{date.format('dd-MM-yyyy')}}</span>

**Comment by marinarose92** [comment]
That's it, thanks so much for your help.
