### ISSUE TITLE
remove date

### ISSUE THREAD

**Issue by akashkoul** [arca-computing/MultipleDatePicker#123]
how can i remove selected date without clicking on calendar

**Comment by mgohin** [comment]
just remove the date from the variable you give to `ng-model`, it's reactive so any change in `ng-model` will be visible on the calendar

**Comment by akashkoul** [comment]
@mgohin is there a trigger from a in which i can pass the date and remove it from client and it's multi-select date picker.

**Comment by mgohin** [comment]
I don't understand your problem, `ng-model` is reactive so : 

    $scope.myArrayOfDates = [your_dates_here];

    var removeDate = function(dateToRemove){
        $scope.myArrayOfDates.splice($scope.myArrayOfDates.indexOf(dateToRemove), 1);
    }

The calendar will update itself when changing `$scope.myArrayOfDates`
