### ISSUE TITLE
Get the value

### ISSUE THREAD

**Issue by edinhorod** [arca-computing/MultipleDatePicker#124]
Hi man, I just wanna get the value of the days when I click in calendar, but I don't know how to do this. When I click, I receive this object: 
1: Moment
_d: Thu Mar 21 2019 00:00:00 GMT-0300 (Horário Padrão de Brasília) {}
_isAMomentObject: true
_isUTC: false
_isValid: true
_locale: Locale {_ordinalParse: /\d{1,2}(th|st|nd|rd)/, ordinal: ƒ, _abbr: "en", _ordinalParseLenient: /\d{1,2}(th|st|nd|rd)|\d{1,2}/}
_pf: {empty: false, unusedTokens: Array(0), unusedInput: Array(0), overflow: -2, charsLeftOver: 0, …}
__proto__: Object

**Comment by mgohin** [comment]
answered in gitter ;)
