### ISSUE TITLE
Limiting the ammount of days user can select. 

### ISSUE THREAD

**Issue by arielramosbuera** [arca-computing/MultipleDatePicker#125]

**Comment by arielramosbuera** [comment]
Sorry. is there a way that we can lets say limit the ammount of days that the user selects to 3? im a newbie. i read abount the 

`$scope.checkSelection = function(event, date) {
    if(somethingWrongWithThisDate(date)){
        event.preventDefault();
        console.log('my click was prevented, want am I gonna do with my life ?');
    }
}`

to check on day-click. 

my issue is i dont know how to get the dates arrange length from within the function so i can do an if statement. again. im a newbie in javascript. 

please help me out.. 


PS. thanks for the incredible piece of code. its exactly what we needed!

**Comment by mgohin** [comment]
Hi,

you pass an array to the directive (http://arca-computing.github.io/MultipleDatePicker/#ngmodel I named it `myArrayOfDates `), so in the checkSelection you can check this array length.

```javascript
$scope.checkSelection = function(event, date) {
    if($scope.myArrayOfDates.length >= 3){
        event.preventDefault();
        console.log('user cannot select more tha 3 dates');
    }
}
```

Let me know if it's ok ;)

**Comment by arielramosbuera** [comment]
Absolute Genius.

i tried everything without the $scope. before myArrayOfDates.length. so i dont feel as bad.

thanks for the quick reply and for your incredible piece of code!

**Comment by mgohin** [comment]
You are welcome ;)

**Comment by arielramosbuera** [comment]
quick follow up. and im sorry to re open the issue. after the user has selected the maximum amount of dates, if the user wants to DE-Select a specific date to choose another one, the code wont let them. once they choose the 3 accepted days the system gets blocked and the user cant choose to remove one day and add another one. 

is this something that could be accomplished or will the user have to simply refresh the page and restart?

thanks!
AR

**Comment by mgohin** [comment]
I'm sorry I did not get notified for the re-opening.
You have to check if the date is already in your date list. If so it means that the user want to deselect it, so you can let him do the action ;)
