### ISSUE TITLE
Assign ng-model or way to pull back selected dates from calendar

### ISSUE THREAD

**Issue by Xal3ph** [arca-computing/MultipleDatePicker#16]
I've developed a few applications in angularjs for the company I work for, however, I consider myself to be a relative beginner.  In any case, I don't see a way of pulling back data from the calendar unless I capture it on the day click event.  If I wanted to pull back the "days" array, what is the best way to do this without hacking the event handler - since this array already exists getting access would be the best method, no?  If there was a way to assign a model or simply assign a scope variable to days (or have selectedDays update the assigned scope variable - not just for preset values) this would help.

Ultimately I want to convert this to a list of date ranges instead of an array of dates for space efficiency.  I figured gaining access to the array would be easier but would include the overall goal in the case you find this to be useful (perhaps it would scale well?).

Thank you for the awesome tool, best of luck and happy coding!

**Comment by mgohin** [comment]
Did you try ?

**Comment by Xal3ph** [comment]
Yes - thank you!

**Comment by ipearx** [comment]
Isn't the whole point of Angular to enable two way binding to such an object? I was surprised that it doesn't  days-selected="selectedDays" didn't mean that $scope.selectedDays would always have the list of selected days in it.

**Comment by mgohin** [comment]
I didn't do it this way to let you the possibility to handle days selection and what you want to do with it, the selectedDays is never changed in the directive

**Comment by mgohin** [comment]
I consider this issue as closed, I you want any improvement please create a new issue ;)
