### ISSUE TITLE
disabling selection

### ISSUE THREAD

**Issue by mez** [arca-computing/MultipleDatePicker#17]
I'd like to pre-populate the date-selected, but also have anymore dates from being selected. I'd like to to apply ng-disabled.

**Comment by mgohin** [comment]
http://arca-computing.github.io/MultipleDatePicker/

You can populate selected days as described in the demo page, for example :

    <multiple-date-picker days-selected="[1404770400000, 1405029600000]"/>

You can set days off : dates that can't be selected, for example :

    <multiple-date-picker days-off="[1404770400000, 1405029600000]"/>

Maybe I don't get what you want, if so please explain it a bit more ;)

**Comment by mez** [comment]
Yup, I have put those options to great use! What I am talking about the behavior an input element would exhibit if you gave it the "disabled" attribute or in angular how the ng-disabled="expression" behaves. I want to still show the selected dates etc, but for certain cases I wan to disable the entire directive for further input all together.

**Comment by mgohin** [comment]
Could you give me a simple example (no code, juste explanation), I'm not sure to get what you mean

**Comment by mez** [comment]
OK, well you know how days-off=[] makes any timestamp in that array not selectable? I'd like to have an easy way to make all the days automatically be not selectable...like an all-days-off='true' option or something.

**Comment by mgohin** [comment]
ok now I understand. I'll add it later in the week I can't do it for the moment ;)

**Comment by mez** [comment]
Awesome! Thanks so much for your time btw :)

**Comment by mgohin** [comment]
Ok I couldn't resist to give you the option ;)
Available in [v1.1.5](https://github.com/arca-computing/MultipleDatePicker/releases/tag/v1.1.5)

**Comment by mgohin** [comment]
251ea55

**Comment by mez** [comment]
Super! I'll give it a try :)

**Comment by mgohin** [comment]
Is it good ?

**Comment by mgohin** [comment]
No news, considering as closed ;)
