### ISSUE TITLE
day-select directive 

### ISSUE THREAD

**Issue by hrizvi** [arca-computing/MultipleDatePicker#20]
Hi,
How can I change date yyyy-mm-dd to timestamp in day-selected directive array?
I don't want to go on the script side as I am using the calendar through ng-repeat for each id so I want a way to change the date to timestamp from your directive. 
Basically I have want to convert this format 2015-03-14T19:00:00Z to time-stamp as per your directive requirement, to show selected days of each unique groups' schedules.

**Comment by mgohin** [comment]
Hi,

just to be sure we are talking about the same problem you have, you want to convert "days-selected" array that is used to pre-select dates on the calendar when you show it up ?

**Comment by hrizvi** [comment]
Yes, The scenario is that when I select a date from the calendar for example 6th of March 2015, it store in db. And when I refresh the page the selected date should show up as marked red. The Date loads up but as your days-selected="[]" directive uses milliseconds timestamp in place of a date format. How would i convert 2015-03-14T19:00:00Z this format to time stamp using this directive? I don't want do it from the script side as I have to show many calendars of different groups using there IDs plus hierarchy is very deep.

**Comment by mgohin** [comment]
```moment("2015-03-14T19:00:00Z")``` gives me a proper moment date, so instead of timestamps, add a liste of string dates ```["2015-03-14T19:00:00Z", "2015-03-14T19:32:00Z", ...]```.

transformation in moment dates is done here : https://github.com/arca-computing/MultipleDatePicker/blob/master/multipleDatePicker.js#L116

Let me know if it works or not ;)

**Comment by hrizvi** [comment]
So your saying that it can use the normal date format as well in the days-selected=[] directive? Because I am storing the date in the normal format.

**Comment by mgohin** [comment]
I use [momentJs](http://momentjs.com) that is a powerfull lib to manipulate dates. I say you should be able to use your date format instead of timestamps, can you try ?
I never did it and don't know if it fits your needs, but it should work

**Comment by hrizvi** [comment]
Well I just did and the behavior is that it is selecting the current date in-spite of showing all the selected dates.

**Comment by mgohin** [comment]
you give the directive something like that ```days-selected=["2015-03-14T19:00:00Z", "2015-03-14T19:32:00Z"]``` ? (sorry I try everything to get the right answer)

**Comment by hrizvi** [comment]
Yeah Sort of!! 
What do you mean (sorry I try everything to get the right answer) ???

**Comment by mgohin** [comment]
sort of ?

I mean I maybe ask stupid questions ;)

**Comment by hrizvi** [comment]
days-selected="['2015-03-13T19:00:00Z']" this what I used if i manually putting the date. 
but i  am using  ng-repeats Alias days-selected="[schedule.events]" in the real scenario .

**Comment by mgohin** [comment]
shouldn't it be ```days-selected="schedule.events"``` ? I suppose that your ```$scope.schedule.events``` is already an array ?

**Comment by hrizvi** [comment]
No its not an array! its a object inside an array!!! thats why using []

**Comment by mgohin** [comment]
schedule.events, sound plural no ?
So what does it contains exactly ?

**Comment by hrizvi** [comment]
schedule" : [
       {
               "_id" : ObjectId("54f86baa1ed53fe0172a4ada"),
               "events" : ISODate("2015-03-13T19:00:00Z")
       }
]

**Comment by mgohin** [comment]
This is a mongodb extract no ?
What do you have exactly in your js script ?

**Comment by hrizvi** [comment]
I just extracted from Mongodb to just give u an idea. 
Well Actually I am making a groups which have n-schedules which further contains schedule as above and n-events are the date which were selected by user previously. I am trying to show these days for n-calendars

**Comment by mgohin** [comment]
In any cases if you want to use the lib as it is now, you must provide a format that will work with moment parsing -> [Moment Parsing](http://momentjs.com/docs/#/parsing/).

Ex : ```days-selected="[1425574268000, 1425574265000, ...]"``` or ```days-selected="['2015-03-13T19:00:00Z', '2015-03-13T18:00:00Z', ...]"```

If you have a complex object, you can use function [Map of Lodash](https://lodash.com/docs#map)

**Comment by mgohin** [comment]
Did you manage to make it work ?

**Comment by hrizvi** [comment]
Yeah it worked but after doing some stuff with data. you can close the ticket
