### ISSUE TITLE
Height Control Method

### ISSUE THREAD

**Issue by hrizvi** [arca-computing/MultipleDatePicker#21]
Hi,

In your calendar's tutorial, there is an option to control the width of the Calendar but there isn't any option to control the height of the calendar. I tried a lot to control the height with CSS but it doesn't seem to work at all. Could you please tell the way in which I could adjust the height along with width of the calendar.

Thank You

**Comment by mgohin** [comment]
Hi,

there is no defined height for the calendar, it's too tricky to calculate height for each cell with a defined height on the global calendar.

You can play with padding on L.57 of the css file :
 
    .picker-top-row, .picker-day {
      padding: 10px 0;
    }

If you want to only change day cells, define in your css file : 

    .picker-day {
      padding: 10px 0;
    }
