### ISSUE TITLE
day-click

### ISSUE THREAD

**Issue by Asopus** [arca-computing/MultipleDatePicker#22]
Hi

I've installed the library and it's looking great. 
Except if I use <code>\<multiple-date-picker day-click="logInfos"/></code> my console keeps telling me 
<code>15:00:50.951 "callback option deprecated, please use dayClick"</code>
whenever I click a cell.
What is causing this error and how can I extract all the selected dates from the picker?

Greets
Asopus

**Comment by mgohin** [comment]
Hi,

the warning is here because the callback option is deprecated, you probably are doing something like `<multiple-date-picker callback="yourCallbackFunc"/>`

As indicated in the doc (--> http://arca-computing.github.io/MultipleDatePicker/) you should use `day-click` like `<multiple-date-picker day-click="logInfos"/>`

For your last question about extracting all selected dates, you must do it yourself in the callback you are giving to day-click, here is an example :

html :

    <multiple-date-picker day-click="updateSelectedDates"/>

js :

    var selectedDates = [];
    $scope.updateSelectedDates = function(event, date) {        
        date.selected = !date.selected; //reproduce the standard behavior
        if(date.selected){
            selectedDates.push(date.valueOf()); //valueOf() will give you the timestamp
        }else{
            selectedDates.splice(selectedDates.indexOf(date.valueOf()), 1); //remove the date
        }
    }

NB : I didn't test this code but you probably get what I mean.

If you are ok, please close the ticket, else just ask questions ;)

**Comment by Asopus** [comment]
Thanks, I got it solved!

I think I found a bug. When you select a few dates and then deselect one of them again and you switch months back and forth they unselected day will be selected again.

Could this be?

**Comment by mgohin** [comment]
Do you use something like livereload ? Someone already add a bug like this.
If you use try to turn it off and check again.

Let me know ;)

**Comment by Asopus** [comment]
I don't use LiveReload!
It's not only on my project but also on the demo of this project
What did that person do to solve that?

**Comment by Asopus** [comment]
As far as I see, whenever I unselect a date, switch months and switch back, they unselected dates will be selected again

**Comment by Asopus** [comment]
You can find a screencapture movie of my problem on wetransfer: http://we.tl/4N5o890Fxg

**Comment by Asopus** [comment]
You can find a screencapture movie of my problem on wetransfer: http://we.tl/4N5o890Fxg

**Comment by mgohin** [comment]
https://github.com/arca-computing/MultipleDatePicker/issues/10

Do you have the same problem on the demo page ? http://arca-computing.github.io/MultipleDatePicker/

**Comment by Asopus** [comment]
I work in firefox and have the same problem in the demo to!
I've asked some of my coworkers to test this issue to on the demo page and they have it also

**Comment by mgohin** [comment]
Oups got it too -_-

Gonna investigate it ;)

**Comment by Asopus** [comment]
Alright, thanks! Let me know if you solved the bug cause I'm eager to use your datepicker :)

**Comment by mgohin** [comment]
Got this little bug ;)
Few minutes to push it

**Comment by mgohin** [comment]
use release 1.1.6 ;)

**Comment by Asopus** [comment]
Thanks, gonna look at it tomorrow!

**Comment by Asopus** [comment]
Thanks, that did it!
