### ISSUE TITLE
Dynamic update days-off

### ISSUE THREAD

**Issue by Asopus** [arca-computing/MultipleDatePicker#23]
Hi

I'm using a scope variable to fill in the days-off on the calender. However when the content of the scope variable changes, the days-off won't update. Is this an issue? Is there any solution to dynamically update the days-off through a scope variable without refreshing the page?

Cheers
Asopus

**Comment by mgohin** [comment]
Hmm strange we are watching this value L128 :

    scope.$watch('daysOff', function() {
            scope.generate();
          }, true);

Can you try going in this watch and debug a bit ?

**Comment by Asopus** [comment]
Okay I'll do that

**Comment by Asopus** [comment]
could if be that in the scope.generate function, the days-off variable isn't set?

**Comment by Asopus** [comment]
nvm, that isn't the issue

**Comment by mgohin** [comment]
I'm gonna try, I let you know

**Comment by Asopus** [comment]
Thanks!

**Comment by mgohin** [comment]
How do you update you days-off ? 

I just tried with the demo page like this : 

    <div><multiple-date-picker days-off="myDaysOff"/></div>

    var cpt = 0;
    var addDaysOff = function(){
        cpt++;
        $scope.myDaysOff.push(moment().date(cpt).valueOf());
        $timeout(function(){
          addDaysOff();
        }, 2000);
    };

  addDaysOff();


Every 2s I add a new dayOff and I can see the changement on the calendar

**Comment by Asopus** [comment]
The scope variable is updated with an API database call (get request). I can see my variable change with {{ daysOff }} on the html page, but the calender only seem to update when I delete one

**Comment by Asopus** [comment]
I found it! :)
From the database, I got a timestamp which needed to be multiplied by 1000 first to be in the right format for the daysOff attribute of the directive!
Was my mistake, excuse me

Cheers!

**Comment by mgohin** [comment]
Ho right, you got timestamp in seconds but in JS it's in milliseconds ;)

No prob, I'm glad to help
