### ISSUE TITLE
How to display a month which is not the current month ?

### ISSUE THREAD

**Issue by ronyrun** [arca-computing/MultipleDatePicker#25]
Hello,
Thank you for this Date Picker.
I have a question for you.

How to display a month which is not the current month ?
Thank you very much for your answer.

**Comment by mgohin** [comment]
Hi and thank you.

There is nothing to do it, you can fork it and do it the way you want, I don't think we gonna add that feature, too complex to handle because people will want to show X months with current month in a certain position etc.

**Comment by ronyrun** [comment]
Yes, I'm heading to show several month by repeating your datePicker for every month.
OK I understand, I thought it was easy do force.

**Comment by mgohin** [comment]
It's not very complicated, it's just that people will want all kind of displays, maybe by doing something flexible but I don't have time right now :(
If you think about a good way to do it and choose how to display it, we could do it

**Comment by ronyrun** [comment]
Yes I'll be very interrested about this type of feature.
@mgohin I'm not an expert of directives also :)

But Yes definitely I would do that, I'll try if you can help :)
I use to be connected on IRC #angularjs on freenode.

Come to talk !

**Comment by mgohin** [comment]
We can talk here, it's dedicated to the directive --> https://gitter.im/arca-computing/MultipleDatePicker

I was thinking about another directive to wrap the multiple date picker, something like

    <multiple-date-picker-wrapper display="[-3, -2, -1, 0, 1, 2, 3]" />

to display 7 months with the current in middle (each number reprensenting difference with current month). Of course we would pass an option parameter to give every pickers options `like day-click`, `highlight-days` etc

I clearly don't have time right now to do it, if you want to participate I can create a repo and add you as contributor. I though a bit about this wrapper if you want to dev, we can talk about it more.

**Comment by ronyrun** [comment]
Amazing way of implementation.

**Comment by mgohin** [comment]
still want to do it ? I still don't have time to do it :(

**Comment by ronyrun** [comment]
Hey, yes definitely.
Same on my side .... I'm finishing my product
but we keep on track !!

**Comment by mgohin** [comment]
I'm currently developing the same MultipleDatePicker with React ;)

**Comment by Freundschaft** [comment]
I'd second that, it would be cool to have an attribute like startMonth that would set the current Month to be shown on the control

**Comment by mgohin** [comment]
> I'd second that, it would be cool to have an attribute like startMonth that would set the current Month to be shown on the control

Not sure if you are talking about a super directive to show multiple multipleDatePicker or current directive. If so It's already possible with `month` attribute ;)

    <multiple-date-picker month="any_timestamp_or_moment_date" />

**Comment by mgohin** [comment]
Using another month than the current is already possible, for any improvement please open a new ticket

**Comment by manolof** [comment]
@mgohin 
the `month` attribute is not working for me. Any idea why? I tried adding the timestamp manually, unix format and with milliseconds, and I also tried a moment date (from a variable in my controller).
It just shows the current month.
Thanks in advance!

**Comment by mgohin** [comment]
can you provide a piece of code (html and js) ?

**Comment by manolof** [comment]
```
$scope.departureMonthDefault = moment($scope.lastDayInUS * 1000);

<multiple-date-picker
	days-selected="departureDatepickerSelected"
	sunday-first-day="true"
	disable-days-after="lastDayInUS * 1000"
	disallow-back-past-months="true"
	month="departureMonthDefault"
	show-days-of-surrounding-months="true"
	fire-events-for-days-of-surrounding-months="true"
	day-click="departureDatepickerClick"
	day-hover="departureDatepickerHover"
	highlight-days="departureDatepickerHighlights"
/>
```

Thanks.

**Comment by mgohin** [comment]
Is `$scope.departureMonthDefault` a good moment date ? 
Have you checked it's value ?

**Comment by manolof** [comment]
If I try to log it, it returns:

`{_isAMomentObject: true, _i: 1472774400000, _isUTC: false, _pf: Object, _locale: t…}`

Which is a valid Moment date.

**Comment by mgohin** [comment]
And what it passed to `$scope.lastDayInUS` ?

I'm on gitter, maybe simplier and quicker to help you https://gitter.im/arca-computing/MultipleDatePicker?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge
