### ISSUE TITLE
Highlight multiple days but select only one day

### ISSUE THREAD

**Issue by waqas-syed** [arca-computing/MultipleDatePicker#26]
I want to be able to highlight a number of days based on some business logic when the datepicker gets rendered on screen but the user be only able to select one day. So that will probably require that the highlighted days be in a different color(e.g., green) and the selected single day be in another color (e.g., red). 

Is this possible? Or even if I can make some edits in the current code to achieve this that would be great!

**Comment by mgohin** [comment]
Use the `day-click` callback to choose to select the date or not.

html

    <multiple-date-picker day-click="selectDayIfPossible" highlight-days="highlightDays"/>

js

    $scope. selectDayIfPossible = function(event, date) {
        event.preventDefault() // prevent the select to happen
        if(canSelect()){ //check if user can select this date
            date.selected = !date.selected
        }
    }
    $scope.highlightDays = [
        {date: YOUR_DATE, css: 'mySelectableClass', selectable: true},
    ];

Then change the css to show dates with default css as not selectable and add css for `.picker-day.mySelectableClass` (check the example *Highlight-days* in the demo page)

**Comment by waqas-syed** [comment]
Thanks. That does give me a solution.

But now there is another issue, I am not able to highlight the selected days, although I am using the exact procedure specified here : http://arca-computing.github.io/MultipleDatePicker/

Can I get a Plunker/Fiddle for any example?

**Comment by mgohin** [comment]
Can you show me your code ? (html, js, css)
We can work on it on a plunkr, would be easy to spot the error together

**Comment by waqas-syed** [comment]
I have worked around on the issue and got what I wanted for now. Will get
in touch if I see a problem again!
