### ISSUE TITLE
Moment.js dependency

### ISSUE THREAD

**Issue by girl1n2** [arca-computing/MultipleDatePicker#27]
Hello,

I tried to use the date picker, and I found the hard way that it depends on Moment.js (http://momentjs.com/), but it is not written anywhere.

It will be more appropriate to specify it in the documentation website (http://arca-computing.github.io/MultipleDatePicker/).

And thank you.

**Comment by mgohin** [comment]
Hello,

if you use bower it'll get all dependencies for you but if you clone the repo it'll not.

I'll add a section about it in the doc ;)

**Comment by mgohin** [comment]
done in 2ef79ea3ca0a28966b6a7dd0fd8864f074e7d836

Thanks for your suggestion ;)
