### ISSUE TITLE
Disabled date still selectable

### ISSUE THREAD

**Issue by vaesbart** [arca-computing/MultipleDatePicker#28]
There's an option to mark one or more dates as disabled. However - as is also seen in the demo - when you click on a disabled date it still triggers an event; i.e. with onClick.

Is it possible to make *not* events trigger on disabled dates ?

TIA
Bart.

**Comment by mgohin** [comment]
It triggers the event if you want to do something even if the date is disabled.
So if you want no events, just add in css `pointer-events:: none` to your disabled class.

**Comment by vaesbart** [comment]
Excellent, didn't think of that. Thanks !
