### ISSUE TITLE
Color markings disappear

### ISSUE THREAD

**Issue by vaesbart** [arca-computing/MultipleDatePicker#29]
Hello, I'll try to explain this possible issue as good as I can...
1) select a startdate (27/08/2015)
2) select an enddate in different month (05/09/2015)
3) go back to first date

You'll see that it appears as deselected (red color marking is gone) - at least in Chromium. Haven't tried with other browsers... Note that the enddate *must* be different month than startdate for this to happen.

**Comment by mgohin** [comment]
Are you using something like livereload ?

**Comment by vaesbart** [comment]
No...no livereload...*but* it is an AngularJS application with React components (jsx).
Selecting a date triggers a custom method where $scope is altered, triggering a forceUpdate() of the page.

However; I just noticed that the enddate doesn't need a different month.
Just select a date (1 will do) -> switch to different month and go back. Marking is gone.

**Comment by mgohin** [comment]
We already had someone with a similar issue and it was because of a reload of the page in dev mode. If you go to the demo page I'm pretty sure you don't have this problem.
Is the datepicker in a React component ?

**Comment by vaesbart** [comment]
Of course you are right, on the demo page this 'issue' does not occur.
The datepicker is not inside a React component, so it shouldn't be touched by it in any way.
At least that's my (limited) understanding of it.

Thanks for your input, any suggestions are welcome... otherwise this can be closed.

**Comment by mgohin** [comment]
What tools are you using in your dev environment ? Grunt, Bower, Gradle ... ?

**Comment by vaesbart** [comment]
Let's see: Bower & npm (dependencies), karma / jasmine (testing)...the usual I suppose...
We do have a gruntfile.js but it is outdated so I don't use that. I just manually compile jsx -> js with jsx command. Don't laugh :-)

**Comment by mgohin** [comment]
I don't have any clue about your problem :(
Do you have the problem if you build your whole project and launch it as in production mode ?

**Comment by mgohin** [comment]
Any news ?
