### ISSUE TITLE
How to clear all selected dates?

### ISSUE THREAD

**Issue by jetta20162** [arca-computing/MultipleDatePicker#33]
Hello,

Is it possible to clear all selected days (e.g. with an event)?

Thanks & Regards

**Comment by mgohin** [comment]
Hi,

    <MultipleDatePicker daysSelected=selectedDays />

and in your event 

    scope.selectedDays = [];

**Comment by jetta20162** [comment]
Ah, thank you very much!

**Comment by jetta20162** [comment]
Hello,

I have an event for selected Days: ```<MultipleDatePicker daysSelected=selectedDays />```
Let's say the calendar is empty and then i click on some days to select them.
If i want to clear the selection  ```$scope.selecedDays = [];``` then it doesn't work. The selectedDays array is always emtpy if i select the days.
In case the selectedDays array contains data (e.g. i filled it inside the code to select days) then it is working.

Am i doing something wrong?

**Comment by mgohin** [comment]
Hello,

related to #32 ?

**Comment by jetta20162** [comment]
I tried it out, here is the example, but still no changes, i can't remove the selected days from the calendar

HTML:
```<multiple-date-picker days-selected="selectedDays" />```
```<button ng-click="_test()">test</button>```

JS:
```$scope._test = function(){
$timeout(function() {
$scope.selectedDays = [];
$scope.$apply();
});
}```

One thing i don't understand is, if i select days in the calendar, the selectedDays array never gets filled with the data. Therefore if i set it to ```$scope.selectedDays = [];``` i can't see any cahnges

**Comment by jetta20162** [comment]
It works only if  i have a predefined array (```$scope.selectedDays = [date,date,date,...]```) and after set it to ```$scope.selectedDays = []``` the calendar gets updated

**Comment by mgohin** [comment]
SelectedDays is only an input, then you have to manage yourself days you select in dayClick.

But I didn't know you were not using daysSelected in the first place. So it's normal nothing changes.
I'll add a emit system to send commands, the first will be 'reset' :D

**Comment by jetta20162** [comment]
This would be indeed very useful since i use the datepicker anywhere in my project :-)
So it should work if i fill the selectedDays array within the dayClick event (if date.selected)

Thanks for your help

**Comment by mgohin** [comment]
Check the demo and v1.3.0, added a factory to easily broadcast reset order ;)

**Comment by jetta20162** [comment]
Working perfect...thank you very much!
