### ISSUE TITLE
Showing days from previous and next months

### ISSUE THREAD

**Issue by katyaskr** [arca-computing/MultipleDatePicker#36]
Hi!  Great calendar, thanks so much!

Is it possible to show days from previous and next months in the current month in the empty boxes? And style them differently.

Thanks!

**Comment by mgohin** [comment]
That's a good idea, I'm not able to do it this week but I'll definitely do it ;)

**Comment by mgohin** [comment]
Annnnnnd it's done in ad09b03 (release 1.3.2), let me know if it's working correctly, check the default behavior too (that it's still working well).

**Comment by katyaskr** [comment]
Thanks! But I tried the new release 1.3.2 and the behavior is sill the same. Diff on multipleDatePicker.js comes back same for both versions. Can you check the zip please?

**Comment by mgohin** [comment]
Don't you have some cache in your browser ? If you check 1.3.2 zip there is no occurence for `emptyLastDays` (it has been removed in 1.3.2 but is present in 1.3.1).

**Comment by katyaskr** [comment]
The browser loads the correct version. Source in developer tools for Chrome shows:  @version: 1.3.2
Is there any option I should set in html?

**Comment by mgohin** [comment]
Yep, check the demo page, it's not set to true by default, because the default behavior was without it

    <multiple-date-picker show-days-of-surrounding-months="true" />

**Comment by katyaskr** [comment]
Yes! That was it. I can see the dates now, thanks!. They are not selectable though :((. Would it be too much of a trouble to make them selectable too? Thanks so much.

**Comment by mgohin** [comment]
Ok, I'll add it too

**Comment by mgohin** [comment]
Can you check the release 1.3.3. Also check the demo to see the 2 new params ;)

**Comment by katyaskr** [comment]
Got the release, thanks so much! The surrounding months days are selectable now. I don't see the 2 new params on the demo page. Am I using the right link?  http://arca-computing.github.io/MultipleDatePicker/

**Comment by mgohin** [comment]
My bad I forgot to push gh-pages branch, should be good :)

**Comment by katyaskr** [comment]
Looks great!  Thanks for your amazing work!  :)))))

**Comment by mgohin** [comment]
You are welcome, I'm pleased to see my calendar used.
Are you using it for an online purpose ? If so can I add you into the section "they use it" ?

**Comment by katyaskr** [comment]
If you are interested in more additions to the calendar (I know you want to keep it simple), there are a few more things that I came across in the last few days that I needed. I am able to implement them in my own code, but here they are in case you are curious.

- Be able to select ranges of dates (so if the person clicked Nov 10 and Nov 13 then Nov 10, 11, 12, 13 are all selected
- Disable selecting dates before today

I am using your calendar to develop a rental booking site. As soon as it's ready I will gladly send you the link to it.  Thanks again!!!!

**Comment by mgohin** [comment]
Can you open 2 new tickets for those ideas ? It'll be easier for me to manage enhancements ;)
