### ISSUE TITLE
Add date range selection

### ISSUE THREAD

**Issue by katyaskr** [arca-computing/MultipleDatePicker#38]
Be able to select ranges of dates (so if the person clicked Nov 10 and Nov 13 then Nov 10, 11, 12, 13 are all selected

**Comment by mgohin** [comment]
So the calendar can be used for only one range selection, because I don't know how to manage multiple range selections in the same calendar

**Comment by katyaskr** [comment]
One range is fine. What I meant was after two clicks on two different dates the calendar would populate days-selected with the range of dates between the two clicked dates (including the two). And on the third click it would clear the days-selected and assume we are selecting a new range. This can be an option that you can turn on in the html. So the calendar can work in two modes: multiple days selection (as it is now) or date range selection. I hope I am making sense :)

**Comment by Freundschaft** [comment]
:+1:  I have a working sample with date range working, but its rather messy
https://gist.github.com/Freundschaft/b2ded0fa3fc43f5b4ecb

**Comment by Freundschaft** [comment]
I created a pull request for range selections (very basic)
https://github.com/arca-computing/MultipleDatePicker/pull/43

**Comment by Targun** [comment]
Awesome, would love to have this added @mgohin.  Thanks @Freundschaft.

**Comment by mgohin** [comment]
Going to check it on Monday, I'm a dad since Feb 5th so wasn't available a lot ;)

**Comment by Freundschaft** [comment]
I also have updated code, but need to restructure and commit that code, will try to do that til monday

**Comment by mgohin** [comment]
Ok guys, I'm available today.

I checked your PR @Freundschaft but it's not quite the demand of @katyaskr.

How should it work for you : 
 (1) I select Fev 2nd then Fev 28th and it selects the range 2 -> 28 (I'm ok with that)
 (2) I select Fev 15th then Fev 10th, what happens ?
 (3) I select Fev 15th and change month, do I keep Fev 15th tracked ?
 (4) If the option is used we will not be able to (un)select a single date, it'll always be a range selection

**Comment by Freundschaft** [comment]
sorry I wasnt able to do a structured PR, here's my current version (unstructured) if you're curious:
https://gist.github.com/Freundschaft/27a843f3405643f859e6
Will do a structured PR hopefully soon as soon as I have time.

(1) that's how I built it
(2) If you select Feb 15th and then Feb 10th, the behavior I implemented follows what most range date pickers do: it selects Feb 10th only and as the start for the range.
(3) yes, in order to allow range selection over multiple months
(4) yes. but I think it will be kind of hard to have a control that offers range and single date at the same time. It should be added as a note that if the range control options are used, the control is only usable in single date afterwards.
Alternatively, it's theoretically possible to only select the start date, then the end date would be undefined, and the surrounding controller could handle that case.

**Comment by cwagner22** [comment]
@Freundschaft Looking forward to your PR. As I needed range selection I used your version and it worked well. I had to modify your code to add a way to get the dates within range though. (Currently the `dayClick()` callback only allows to get the start and end date.)

**Comment by mgohin** [comment]
I'm not available at this time, a lot of work but will look into it as soon as possible. If you do a PR it would be nice.
Will add a callback like `rangeSelected`

**Comment by adil-devacc** [comment]
@mgohin Have you merged it or not? Please do it soon as I am in need of this feature too. Date range selection must be the very needed feature of a multi select calendar.

**Comment by adil-devacc** [comment]
@cwagner22 Can you show your version with modification of @Freundschaft ? That will be really great and let us know how you have handled range selection?

**Comment by mgohin** [comment]
I'm sorry guys I'm very overworked at this moment, don't have time to check it out, if we could have a clean PR I'd be glad to merge it.

**Comment by cwagner22** [comment]
I'm currently in holidays. I will try to clean my code this weekend to share what I have but I'm not sure it's ready for a PR yet. (Probably some bugs to fix)

**Comment by cwagner22** [comment]
I'm currently on holidays. I will try to clean my code this weekend to share what I have but I'm not sure if it's ready for PR yet (Probably some bugs to fix)

**Comment by adil-devacc** [comment]
@cwagner22 Dude have you got some time to create a PR? If not can you please share your version and little description how to manage to do that? Will be grateful.

**Comment by Freundschaft** [comment]
I updated the gist and fixed a bug that existed during seleciton causing visual glitches, and working towards a PR

**Comment by Freundschaft** [comment]
I updated the PR at https://github.com/arca-computing/MultipleDatePicker/pull/43

**Comment by mgohin** [comment]
let me check ;)

**Comment by mgohin** [comment]
I'm gonna merge it right now and make a release, let me know if something wrong.
So you can still use this datepicker ;)

**Comment by cwagner22** [comment]
Well FYI this is my current version: https://github.com/cwagner22/MultipleDatePicker/blob/master/multipleDatePicker.js

I was going to do some tests and code cleaning but I'm having some issue with my environment.

**Comment by mgohin** [comment]
Available in 1.4.2 : https://github.com/arca-computing/MultipleDatePicker/releases/tag/v1.4.2

**Comment by mgohin** [comment]
@Freundschaft can you provide an example ? not quite sure it's what requested @katyaskr

**Comment by Freundschaft** [comment]
<multiple-date-picker date-range="trip.dateRange" range-start="stopovers[0].departure" range-end="stopovers[stopovers.length - 1].arrival"/>

is an example on how to use it.

date-range containes a moment range object that contains the range of the selected dates.
range-start contains the start date of said range for direct binding
range-end contains the end of of said range for direct binding

**Comment by mgohin** [comment]
with your way of doing it you must have a preselected range of dates ?

**Comment by Freundschaft** [comment]
its two way bound, so binding an existing value to range-start and range-end should just work

**Comment by mgohin** [comment]
but what if I want to enable range selection but don't have any preselected date ?

**Comment by Freundschaft** [comment]
I think then binding to an empty scoped variable should work, not sure if I tested it though.

**Comment by mgohin** [comment]
I removed 1.4.2 because it doesn't fit the request and isn't working well

**Comment by Freundschaft** [comment]
what is not working well? and what is not fitting the request? I can make adjustments.

**Comment by mgohin** [comment]
You should use an option to enable or not date range selection, binding an empty scope variable isn't quite clear.
Sorry I said it wasn't working, it's not what I meant, you should test your solution to be sure it's working, then I'll try it on the demo page and then push it to a release.

**Comment by Freundschaft** [comment]
no worries, I can make the range usage flag explicit and add some samples to the demo
:+1:

**Comment by mgohin** [comment]
Hi,

digging out this topic (too), now with combination of `ng-model` and `ng-click` you should be able to select any dates you want.
