### ISSUE TITLE
Disable selecting dates before today

### ISSUE THREAD

**Issue by katyaskr** [arca-computing/MultipleDatePicker#39]

**Comment by mgohin** [comment]
Done in release 1.3.4.
I added `disableDaysBefore` and `disableDaysAfter`

**Comment by katyaskr** [comment]
I installed 1.3.4 and added the disable-days-before="today" to html. The dates aren't getting disabled for some reason. I can see it working in your demo page though. Is today supposed to be defined in my code somewhere? Thanks!

**Comment by mgohin** [comment]
Hehe, today is a scope var

    $scope.today = moment();

If it was a string it would have been `disable-days-before="'today'"` (notice the simple quote surrounding today)

**Comment by katyaskr** [comment]
Of course!  I got it now. Thanks!

**Comment by mgohin** [comment]
NB : you can use any date ;)
