### ISSUE TITLE
Disable days before

### ISSUE THREAD

**Issue by AlexEntrepreneur** [arca-computing/MultipleDatePicker#40]
Hi Guys,

I'm not sure whether it is me, but when I have set disable-days-before="today" as following the example etc. it does not disable the days or highlights "today" until I click one month forward then back again. After that, everything works fine.

I am using this directive on mobile, using Ionic Framework.

Thanks! :blush: :+1: 

Alex

**Comment by mgohin** [comment]
Hi,

I don't know why it's behaving like that, maybe because of Ionic ? If you did like in the demo page ...

Maybe you could try to debug it with the non minified version ? Sorry, I don't have much time those days :/

**Comment by AlexEntrepreneur** [comment]
@mgohin No Problem!

Great Directive btw :blush:

**Comment by mgohin** [comment]
Let me know if you find anything.

And thx ;)
