### ISSUE TITLE
Dont show previous month row.

### ISSUE THREAD

**Issue by RazaTayyab** [arca-computing/MultipleDatePicker#44]
If we select Sunday as a first day of the calendar. When a months have start with Sunday than it prints complete empty row above the month. Logically Sunday as calendar first day and start of the month is also Sunday than the previous dates are not visible to user as empty row.

**Comment by mgohin** [comment]
I'm going to check it on Monday ;)

**Comment by adil-devacc** [comment]
@mgohin Similarly it isn't showing next month. Like today is last day of march and I want to select first date of next month or any date of next month, it doesn't change month. How to change month?

**Comment by mgohin** [comment]
@adil-devacc I think this isn't related to @RazaTayyab issue.

Check the doc for `Show previous/next month days`. Then when there is a click, you'll have to check if you clicked on a previous/next month's day, if so you can change month this way : 

html

    <multiple-date-picker month="myMonth" />

js

    $scope.month = YOUR_DATE; //use a valid date

**Comment by mgohin** [comment]
@RazaTayyab sorry for the delay, should be fixed in v1.4.1 : 25c7425

**Comment by AndersWinther-Dahl** [comment]
Ahh, I see. That could be a fine work around. But I would love to see your media query fix too :-)
Thanks!

**Comment by mgohin** [comment]
I guess you responded to the wrong issue ;)

**Comment by AndersWinther-Dahl** [comment]
Oups, sorry :-)
