### ISSUE TITLE
Use MultipleDatePicker as a single date picker

### ISSUE THREAD

**Issue by rathjung** [arca-computing/MultipleDatePicker#45]
Hello,

My website have two calendar, one which allow user to selected multiple date and one which allow a single date. I've implemented MultipleDatePicker to the multiple one. So I think I could use the same for the single one.

I've bound a callback to a dayClick event. Inside the callback, I've call the  multipleDatePickerBroadcast.resetOrder service. But after the service run, I can't selected any date.

I've tried another way by removing the class 'picker-selected' from all elements that contain it right after the callback run. But if I go to other months and go back, the class is come back.

I've tried many ways, but nothing works for me.

So could you please suggest some advice to me about how to do this ?

Thank you,
Rath

**Comment by mgohin** [comment]
Hi,

did you provide an ID to your calendar like in the demo in _Emit reset_ (http://arca-computing.github.io/MultipleDatePicker/) ?

**Comment by rathjung** [comment]
yes, I already provided an ID.

**Comment by mgohin** [comment]
Did you provided an ID to both calendars and different ones (I guess you did) ?

**Comment by rathjung** [comment]
Yes, I did it.

**Comment by mgohin** [comment]
Join here to talk please
https://gitter.im/arca-computing/MultipleDatePicker?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by rathjung** [comment]
Thanks ! :D

**Comment by mgohin** [comment]
Are you there ? Maybe you are at work.
I'm at work so I'll be absent sometimes, don't worry I'll not let you down :p
Let's speak on gitter, it'll be better to exchange and help you
