### ISSUE TITLE
reset MDP to current month

### ISSUE THREAD

**Issue by jetta20162** [arca-computing/MultipleDatePicker#46]
Hi,

is it possible to add an option to set the MDP to current month within "multipleDatePickerBroadcast.resetOrder"? Or is there another way to set the current month of the MDP with JS?

Thanks & Best regards,
Thomas

**Comment by mgohin** [comment]
html

    <multiple-date-picker month="myMonth" />

js

    $scope.month = moment(); //now

Let me know if it's ok

You can change $scope.month when you want :)
