### ISSUE TITLE
Click Reset isn't with days selected

### ISSUE THREAD

**Issue by adil-devacc** [arca-computing/MultipleDatePicker#47]
Hi, 

I want to show only clicked as highlighted and all other days and UN-highlighted. Here is my scenario, when Page is loaded,some dates are highlighted using `days-selected="selectedCalendarDays"`. Now I want when user clicks, all selected highlighted days becomes un highlighted and only clicked one remains as highlighted. So I set `selectedCalendarDays` as empty. But now when I click again the previously highlighted day remains highlighted. I only want to highlight the clicked date, some thing similar to this [issue](https://github.com/arca-computing/MultipleDatePicker/issues/45). Here is my code.

`<multiple-date-picker calendar-id="shippingCalendar" day-click="selectShippingMethod" days-selected="selectedCalendarDays" week-days-off="[0, 6]"/>`

And here is my controller code of `selectShippingMethod`

    $scope.selectShippingMethod = function(event, date) {
          event.preventDefault();
          $scope.selectedCalendarDays = [];
          multipleDatePickerBroadcast.resetOrder('shippingCalendar');
          date.selected = !date.selected

      }

If I comment `date.selected` line, nothing is shown. I have interchanged lines of date.selected and `multipleDatePickerBroadcast.resetOrder` but result is same. I have also tried 

`$scope.clicReset = function(){
                                  multipleDatePickerBroadcast.resetOrder('shippingCalendar');
                              };`

Can you please guide me how I can achieve this?

**Comment by mgohin** [comment]
Just to resume what I understand : you pre-highlight some days but when user clicks a day all days are unhighlight and only the clicked one remains highlight am I right ?

Your problem is that all days even the clicked are unhighlight ?

**Comment by adil-devacc** [comment]
No. You calendar is multiselected. So I want to work it as single selector too. For example once I click on 3, date 3 is highlighted. Now when I click 4, date 4 is highlighted along with 3. Now what I want when 4 is clicked previously selected/highlighted 3 becomes un highlighted.

**Comment by mgohin** [comment]
Can you try this

    $scope.selectShippingMethod = function(event, date) {
        event.preventDefault();
        $scope.selectedCalendarDays = [];
        multipleDatePickerBroadcast.resetOrder('shippingCalendar');
        $timeout(function(){
            date.selected = !date.selected
        });
    }

**Comment by adil-devacc** [comment]
Tried. But same result. Previously selected remains selected.

**Comment by mgohin** [comment]
Have you set the `calendar-id="'shippingCalendar'"` property in the html ?

**Comment by adil-devacc** [comment]
<multiple-date-picker calendar-id="'shippingCalendar" day-click="selectShippingMethod" days-selected="selectedCalendarDays" week-days-off="[0, 6]"/>

**Comment by adil-devacc** [comment]
`<multiple-date-picker calendar-id="'shippingCalendar" day-click="selectShippingMethod" days-selected="selectedCalendarDays" week-days-off="[0, 6]"/>`

**Comment by mgohin** [comment]
Your forgot a quote at the end of shippinCalendar, copy/paste error ?
 `calendar-id="'shippingCalendar'"`

**Comment by adil-devacc** [comment]
I have even tried that. :) Doing this it doesn't select any date even the clicked one.

**Comment by mgohin** [comment]
I'm gonna try on my side to reproduce and debug it

**Comment by adil-devacc** [comment]
ok. I am waiting. :)

**Comment by mgohin** [comment]
Found something ;)

    $scope.selectShippingMethod = function(event, date) {
        event.preventDefault();
        $scope.selectedCalendarDays = [date];
        multipleDatePickerBroadcast.resetOrder('shippingCalendar');
    }

**Comment by adil-devacc** [comment]
Well thats the one.  Instead of  `$scope.selectedCalendarDays = [date];` it should be `$scope.selectedCalendarDays = [date.valueOf()];` 
And it has solved problem. Thank you and Thumbs up :+1:

**Comment by mgohin** [comment]
Yep you are right, It'll avoid problems ;)

Thanks for using the lib and helping me improve it.

**Comment by mgohin** [comment]
Please check the doc : http://arca-computing.github.io/MultipleDatePicker/

I added an example you should check because you'll not be able to unselected the selected day if you keep the code as I wrote it.

**Comment by adil-devacc** [comment]
Sure. You are welcome. As I am using it so I will be asking again and again if I am in need of some thing.

**Comment by mgohin** [comment]
No problem, I may be busy sometimes, but when I got time I'll answer tickets
