### ISSUE TITLE
Cannot select more than 2 dates

### ISSUE THREAD

**Issue by bharathitman** [arca-computing/MultipleDatePicker#48]
I am using angular 1.4.9, it seems that selecting more than 2 dates resets the calendar (a simple default use case without any additional code). Any idea about this?

**Comment by mgohin** [comment]
I just tried on the demo page with `https://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.min.js` and don't have any problems.

Are you using livereload ? :)

**Comment by bharathitman** [comment]
Yes, browser-sync + gulp

**Comment by bharathitman** [comment]
Very strange, works fine in test projects. The project in which I want to use this is kinda huge (this won
t matter) and has ui-bootstrap

**Comment by mgohin** [comment]
Try to use it without livereload and should be working ;)

**Comment by mgohin** [comment]
Did you manage to solve your problem ?

**Comment by bharathitman** [comment]
Hi, created a build and uploaded it on a server. Same problem

**Comment by mgohin** [comment]
Possible to get access to check with debug ?
Can you use the non minified version to simplify the debug ?

**Comment by bharathitman** [comment]
I am currently on a vacation. Will look into this when I get back this weekend :)

**Comment by mislamov** [comment]
Hi, same situation.
Angular 1.5.5

in html:
<multiple-date-picker/>

in console (after select 3th day):
angular.js:13550 TypeError: moment.range is not a function
    at Scope.scope.toggleDay (multipleDatePicker.js:285)

**Comment by mgohin** [comment]
got it, 2min to fix it

**Comment by mgohin** [comment]
I merged a wrong PR so I removed the tag but not properly, sorry.
Please use last version 1.4.1 and not 1.4.2, should be working. 

Let me know :)

**Comment by mislamov** [comment]
looks like 1.4.1 works fine :)
