### ISSUE TITLE
ng-model

### ISSUE THREAD

**Issue by rohdef** [arca-computing/MultipleDatePicker#50]
Hey so far it's looking quite good. A good phrase to consider when designing an api of some kind is:

"Have you used it in anger, yet", basically meaning can you get it  to work easily and fast without any issues (eg you could look here http://homepages.inf.ed.ac.uk/wadler/topics/functional-programming.html). Does it work easily and as expected when you're stressed and do not have the time to read the documentation.

However, good as the start is, there is some things to be desired. I have spent +15 mins on your documentation and I still do not know how I'm supposed to bind the dates to my model or get the selected dates. The closest I've come is an event for when one selects the dates.

My first request falls on the way of using the MultipleDatePicker. As an Angular user I expect it to have the ng-model attribute to bind the pickers moment objects to my model, probably through an array. May I kindly suggest you add this, as it will greatly improve the experience from angular users, especially those "using it in anger".

**Comment by mgohin** [comment]
Hi,

thanks for all you suggestions. You are right, I don't know why I didn't use `ng-model` in the first place.
I'll probably upgrade the directive to a new level 2.0 with that kind of changes, will change the demo page too.

Let me some time to do it, I work all week days so I need to find some time to do it ;)

**Comment by mgohin** [comment]
What about https://github.com/arca-computing/MultipleDatePicker/releases/tag/2.0.0 ? :)

Can you check the demo page too please ?

**Comment by rohdef** [comment]
Probably slip of mind, happens to us all :) Just tested it from the link you sent, seems to work perfectly. Thanks a lot for the fast update. Will keep you updated if I discover any more potential improvements. So far I'm very pleased, thanks for a great job, keep it up.
