### ISSUE TITLE
Documentation - how to get the dates

### ISSUE THREAD

**Issue by rohdef** [arca-computing/MultipleDatePicker#51]
In relation to my previous issue: https://github.com/arca-computing/MultipleDatePicker/issues/50

As said before I like the DatePicker, so please don't take the issues as being criticism or anything like that.

A suggestion for the documentation. You have a really nice "Time to use it" section. I feel this would be greatly improved if you after "Add it in you html" have a section on how to get the dates. If the event handler currently is the right way (I suspect so from my current going through the doc) it would be really nice to have it right after adding it to the html. Then I can worry about options when the basics are working.

**Comment by mgohin** [comment]
Is the new demo page speaking or I need to add a section ?

**Comment by rohdef** [comment]
It's the first option I see, so it's perfect :) A minor detail, I just noticed that a typo has found its way to the index, where Options ended up as Pptions. Once again +10000 :+1: from here.

**Comment by mgohin** [comment]
Many thanks.
The typo will be fixed and commit in the week
