### ISSUE TITLE
Default timezone

### ISSUE THREAD

**Issue by rohdef** [arca-computing/MultipleDatePicker#53]
A nice and hopefully simple option for you to make is to provide a default timezone to the date objects. Forcing them to e.g. midnight in Europe/Paris, to ensure a consistent way of sending dates.

I'm not sure what time zone it's using now, but if just doing the default I recall that moment defaults to the browsers zone. This can cause issues when e.g. creating a booking system, for someone in say Bordeaux, France, is doing bookings for something home in France, while being in Romania. The errors arise because if the computer can be set the timezone to Romanian time all dates would end up the day before when viewed home in France, causing all bookings to be off. Ofc. in some use cases this might be desired, but in a lot of cases, such as booking the desired option is to lock the time to some desired default.

**Comment by mgohin** [comment]
Shouldn't users use `moment.tz.setDefault(TIMEZONE);` ? (with moment-timezone)
So all their moment dates will be good ?

**Comment by rohdef** [comment]
Hmm might actually be appropriate indeed. Hadn't spotted that one. Currently I can't think of a use case where a deviating timezone is desired for the calendar. I guess that's a better solution then.
