### ISSUE TITLE
days-allowed feature

### ISSUE THREAD

**Issue by vivekpurushoth** [arca-computing/MultipleDatePicker#54]
Currently we have days-off feature. Any dates we give to this list will be disabled and the user cannot select it.

But if we want to do the reverse, we only want to allow certain dates, then we have to manually calculate all the dates that we do not allow.

Instead could we just have an opposite parameter like days-allowed. If this is set, then all the other dates will be disabled.

**Comment by mgohin** [comment]
That should be possible, will try tomorrow - this week for sure (France here and going back home right now)

**Comment by mgohin** [comment]
done and available in 2.0.1 ;)

**Comment by AndersWinther-Dahl** [comment]
Cool feature!
Tried it, but for me it only works if I initializes the ng-model in the controller to something (empty array or array of values). Otherwise all days seems selectable.

**Comment by AndersWinther-Dahl** [comment]
I'm not that sure that it's the init of ng-model, that makes it kick in (placebo). It's more like that when routing from one page to another it doesn't work. But when refreshing the page, on that page that contains the calendar, then it works.

**Comment by mgohin** [comment]
hmmm don't you have any variable reference interfering with the calendar ?

**Comment by AndersWinther-Dahl** [comment]
I modified a Plunk with routing. And it works:
https://plnkr.co/edit/0yUlObafbh3kFTxQOo7r?p=preview

It must be my code that is error prone.
Sorry for my faulty report

**Comment by mgohin** [comment]
No problem, if you find anything to prevent that kind of problems, let me know ;)

**Comment by AndersWinther-Dahl** [comment]
I think I found the problem. When I use ng-animate the problem happens:
http://plnkr.co/edit/SxSDOSx4yVDYAT5nEZaj?p=preview

See for yourself, remove 'ngAnimate' in example.js, and then it works.

Do you know what to do about it?

**Comment by mgohin** [comment]
I add too much problems with ngAnimate in past, I never use it for complex projects/libs.
I'm sorry I don't have much time to investigate :s

**Comment by AndersWinther-Dahl** [comment]
Hi,
I took another look. And I think I found the problem.
In the template you're using both class and ng-class attributes, that's fine, but when you put an expression in the class-attribute it somehow conflicts with ng-animate.

I changed the line (https://github.com/arca-computing/MultipleDatePicker/blob/master/multipleDatePicker.js#L138) to
`'<div class="text-center picker-day" title="{{day.title}}" ng-repeat="day in days" ng-click="toggleDay($event, day)" ng-mouseover="hoverDay($event, day)" ng-mouseleave="dayHover($event, day)" ng-class="[!day.mdp.otherMonth || showDaysOfSurroundingMonths ? day.css : \'\',day.mdp.otherMonth ? cssDaysOfSurroundingMonths : \'\',{\'picker-selected\':day.mdp.selected, \'picker-off\':!day.selectable, \'today\':day.mdp.today,\'past\':day.mdp.past,\'future\':day.mdp.future, \'picker-other-month\':day.mdp.otherMonth}]">{{day ? day.mdp.otherMonth && !showDaysOfSurroundingMonths ? \'&nbsp;\' : day.date.format(\'D\') : \'\'}}</div>' +`
and then it works.

You can see that I moved the two expression inside the ng-class.

Best regards,
Anders

**Comment by mgohin** [comment]
Nice, I'll make the update now :)

**Comment by mgohin** [comment]
Fixed in 2.0.7 but I your solution doesn't work, it does not apply css correctly.
I moved it in a function, html is clearer that way, should have done it a long time ago :)

Let me know if it fixes your problem

**Comment by AndersWinther-Dahl** [comment]
Everything is working fine now.

Thank you !
