### ISSUE TITLE
Multiple event types

### ISSUE THREAD

**Issue by rohdef** [arca-computing/MultipleDatePicker#55]
Well trust users to come with all the good ideas. A request from the primary user on what I'm working on that I kind of like/dislike, in part I'm not fond of the added complexity however it kind of do make sense.

The idea basically is to have multiple event types to add to the calendar. A case could be having two types of events, say private and work. For instance having the private as green and work as red. As far as I can figure the logical implementation would be something like:

```
<multiple-date-picker ng-model="selectedDates" event-type="eventType" />
<select ng-model="eventType">
    <option value="work">Work</option>
    <option value="private">Private</option>
</select>
```

Then the selectedDates model would be an array of calendar objects, with the date and the type as elements:

```
{
    date: momentFromCalendar,
    eventType: $scope.eventType
}
```

or something like that. As for styling I think adding a css class with the name `mdp-eventType` would make sense. Perhaps using toString() when inserting eventType to allow objects too, althought that may introduce complexities.

Having a more complex version as suggested would also require the `date-click` to be updated appropriately to allow things like switching the event type based on the currently selected. One could imagine an interface where clicking a date once marks it as work, clicking it again marks it as private and a third time to remove it again.

As far as I see it the down side of this idea is that it will make the calendar slightly more complex. This may in part be mitigated by just defaulting to an array of moment objects when `eventType` is not set, however again introducing issues if alternating between set and not set (perhaps detecting it and throwing an error in this case?).

On the up side it would allow a fair deal more complex use cases, such as the one I currently have as a suggestion (a bit more complex than work/private, but still). Also structuring it with objects like this will allow very flexible systems. Imagine adding a `text` property to the objects to insert text in the calendar `badge` etc. Even further, allowing the idea to wonder into a possibility of a future one could even imagine a template system like:

```
<multiple-date-picker ng-model="selectedDates">
    <div class="calendarEntry">
        <h1>{{entry.title}}</h1>
        <p>{{entry.myPersonalText}}</p>
    </div>
</multiple-date-picker>
```

allowing an extremely flexibly system for whatever the heart desires.

I'm not certain about the basic suggestion although there's some cool options in what it allows. Part of me kind of likes the added flexibility and feels that the cost isn't that high. Part of me doesn't like it because it can fast become adding this and that, and the nice and simple way to use this feels really good. If it can be done keeping it in the spirit of AngularJS with having it simple and intuitive, it might be a really good idea.

What say you?

**Comment by rohdef** [comment]
As a side note if this is to be done it should probably be as consistent with the objects for [`highlight-days`](http://arca-computing.github.io/MultipleDatePicker/#highlight-days) as possible

**Comment by mgohin** [comment]
Thanks for all your suggestions, I really appreciate it.

Using the transclude to add html in a day is a very good idea and maybe we can merge both ideas : if you want to add something that come from outside (let's say a selectbox in a popin when you click a date), you use the transclude possibility and add a ng-click on it where you call a directive function and provide a callback that the directive will call with a promise, so you can check whatever you want in your callback, when promise is resolved, your changes will be applied.

Don't know if my idea is quite clear, it' 8:00AM :)

**Comment by mgohin** [comment]
I think we shouldn't use transclude, we should use a ng-template attribute, because we expect transclude html to be shown in addition of the date picker

**Comment by rohdef** [comment]
I think the ng-template would be really cool, then there's just the need for a good way to specify an appropriate model. It would be really nice it it can be somehow be kept centric on the model, so UI logic and model logic won't be mixed together. Perhaps something like this can be done:

    <multiple-date-picker ng-model="selectedDates" model-field="myDate" ng-template="foobar.html" />

I'm fairly new to angular though, so I'm unsure what would make most sense, but one potential issue I can see would be the name of the model inside the template (I assume that we do not want to merge it into `$scope` as one might desire a controller on the template). Perhaps a structure like this would be smart:

    <multiple-date-picker ng-model="selectedDates" model-name="foo" model-field="myDate" ng-template="foobar.html" />

Then the model could be something like:

    {
        myDate: moment(),
        eventType: "private",
        coordinator: new employee(),
        ....
    }

And people could make templates like:

    <div ng-class="foo.eventType">
       {{day}}
       <div class="badge">{{foo.coordinator.initials}}</div>
    </div>

Or what one feels like. I too hope that my idea is clear :)

**Comment by mgohin** [comment]
Maybe in addition of the `ng-template` user could call a callback he provides which do the job he wants.

    <multiple-date-picker ng-model="selectedDates" ui-callback="myUiCallback" ng-template="foobar.html" />

js controller scope function

    /* 
        date : moment date
        key : something provided in template to know what we are asking
    */
    $scope.myUiCallback = function(day, key){
        if(key === 'foo'){
            return day.foo;
        } else if (key === 'displayDate'){
            return day.date.format('YYYY-MM');
        }
        return somethingelse;
    }

template :

    <div>
         <h1>{{uiCallback(day, 'foo')}}</h1>
         <span>today : {{uiCallback(day, 'displayDate')}}</span>
    <div>

**Comment by rohdef** [comment]
It looks like a really good idea :)

**Comment by rohdef** [comment]
Woops, sorry, hit the wrong button :/

**Comment by mgohin** [comment]
Hi,
digging out the topic a bit.
Now we use `ng-model` so user can prevent event with `ng-click` callback, and in this callback shows like a popin to ask date type (work, private), then user add the date in `ng-model` so it select the date in calendar and the type is set.

What do you say @rohdef ?
