### ISSUE TITLE
Show days for next month

### ISSUE THREAD

**Issue by adil-devacc** [arca-computing/MultipleDatePicker#57]
Hi, 

I want to show different number of days for next month. I have seen `show-days-of-surrounding-months="true"` but this isn't what I need. I want to show different number of days of next month. For example some times I want to show 3 days of next month, some times I need to show 10 days of next month and so on. Is there any hook or method available for this?

**Comment by mgohin** [comment]
Hi,

today there is nothing to allow you to do it, and I don't have time to do it sorry, you can fork the project, do what you need and if you want you can share it with us with a PR :)
