### ISSUE TITLE
ng-class inside ui bootstrap modal

### ISSUE THREAD

**Issue by benfortenberry** [arca-computing/MultipleDatePicker#58]
This may be a niche case but I had an issue where inside of a ui bootstrap modal, the ng-class for the selected days was not firing at all. I circumvented the issue by putting an angular variable inside the plain class tag and after scope.generate I did a for each to apply where selected was true. This is my code:

 class="text-center  {{day.calendar-highlight}} picker-day"

  scope.generate();
   angular.forEach(scope.days, function (item, value) {
                          
                            if (item.mdp.selected)
                                item.calendar-highlight= 'calendar-highlight';

                        });

I also added this after the month change to retain the highlighting. There may be a much better way of doing this but I wanted to post so future devs may avoid my headache for past 2 days.

**Comment by mgohin** [comment]
Isn't it a digest problem ?

I don't get why only the ng-class isn't not firing and anything else is working

**Comment by benfortenberry** [comment]
I am not sure, it could be, I get fuzzy with these modal scopes.

**Comment by benfortenberry** [comment]
The model is perfectly fine and functionality is fine except for ng-class. I even just put true for evaluation and nothing happens. But like I said, this could be a niche combination, I love the control btw.

**Comment by mgohin** [comment]
Hmm, don't know where it can come from and don't have time to investigate sorry (busy at work).
If you find anything else, let me know ;)
