### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by jetta20162** [arca-computing/MultipleDatePicker#60]
is it possible to programmatically switch the month / day names from Latin to Chinese characters?

**Comment by mgohin** [comment]
Because it uses [MomentJS](http://momentjs.com/docs/) you can change the language easily

    require('moment/locale/fr'); //or insert this file in your html file in a script tag
    moment.locale('fr'); 

Note : be sure to add the moment locale file before

**Comment by jetta20162** [comment]
Thanks. Is there a way to update the MDP **after** i change moment.locale dynamically? (after MDP is created) I tried to redraw the MDP but it didn't work.

**Comment by mgohin** [comment]
Hmmm not there is not option to do that :/
I'll add a watch on moment locale to redraw days of week, gonna do it now :)

**Comment by jetta20162** [comment]
Thank you very much :-)

**Comment by mgohin** [comment]
Gonna deliver at lunch (France).
I update the demo page too :)

**Comment by mgohin** [comment]
Done in [2.0.3](https://github.com/arca-computing/MultipleDatePicker/releases/tag/2.0.3)

Please let me know if it's ok. I updated the [demo page](http://arca-computing.github.io/MultipleDatePicker/#momentjs-locale)

**Comment by jetta20162** [comment]
Thank you very much. I will test it on monday whe i'm back in the office and give you feedback then. Have a nice weekend! :-)

**Comment by jetta20162** [comment]
It is working perfectly, thank you very much!
