### ISSUE TITLE
picker-day-today is applied to today cell only after first click

### ISSUE THREAD

**Issue by marcolino** [arca-computing/MultipleDatePicker#61]
picker-day-today is applied to today cell only after first click

**Comment by mgohin** [comment]
If I check on the [demo page](http://arca-computing.github.io/MultipleDatePicker/) the `.picker-day.today` css (and not `.picker-day-today`) is always applied.
Do you have the problem on the demo page too ? If so what is you browser ?

**Comment by marcolino** [comment]
No, sorry, in the demo it's o.k. I'll double check my changes... :-(
