### ISSUE TITLE
How to get UTC dates?

### ISSUE THREAD

**Issue by marcolino** [arca-computing/MultipleDatePicker#62]
I live in Italy (UTC+2).
When I select a date, I always get the date of the previous day, at 22:00:00.
How to get the selected day at 00:00:00 (UTC), indipendently from the locale timezone?

**Comment by mgohin** [comment]
It's a moment date, so you just have to use you_date.utc() to get it in UTC time.
You can check all options for moment dates here : [http://momentjs.com/docs/](http://momentjs.com/docs/)
