### ISSUE TITLE
One Day Selection Only

### ISSUE THREAD

**Issue by matrix45** [arca-computing/MultipleDatePicker#64]
Is it possible to allow the user to be able to select a limited number of days based on a dynamic value? 

Sometimes 2, Sometimes 3 depending on an Int being passed.

**Comment by mgohin** [comment]
Yes, with [dayclick](http://arca-computing.github.io/MultipleDatePicker/#dayclickdayhover) callback you can prevent a selection from happening.
You can check how many dates are already selected by checking the variable you passed in `ng-model` :)

**Comment by mgohin** [comment]
Any news ?

**Comment by matrix45** [comment]
I was not able to figure it out. However, I made a work around setting outside parameters and added other limitations.
