### ISSUE TITLE
¿How show all 12 months calendars in a single page?

### ISSUE THREAD

**Issue by falinsin** [arca-computing/MultipleDatePicker#65]
We need show all 12 month in a angularjs view so the users can view all calendars and select some days in some moths.

How woud you do it? 

The idea is print 12 calendars January to December . You show how select a month from actual but is there an option of pass directly year and month so we can print all 12 months.

Sorry my English an thanks in advance for your help and your work

**Comment by mgohin** [comment]
Hi,

you use the directive 12 times and give those 12 directives 12 different months.

    var months = [],
          date = moment().month(0),
          januaryNextYear = date.clone().add(1, 'year');
 
    for(; date.isBefore(januaryNextYear, 'month'), date.add(1, 'month')){
        months.push(date.clone());
    }

    $scope.months = months;

and in your html

    //you could use a ng-repeat if you want
    <multiple-date-picker month='months[0]'></multiple-date-picker>
    <multiple-date-picker month='months[1]'></multiple-date-picker>
    <multiple-date-picker month='months[2]'></multiple-date-picker>
    ...
    <multiple-date-picker month='months[11]'></multiple-date-picker>

**Comment by mgohin** [comment]
Any news ?

**Comment by marinarose92** [comment]
Hello! I am trying to accomplish exactly what the user above asked, and it is giving me a syntax error in the code you provided. Specifically it's the line beginning with `for(;`. It seems to think there's an extra parentheses? If you could offer any advice I'd be appreciative.

**Comment by mgohin** [comment]
Hi, you are right, can you check the code again, I changed it (but did not tested it)

**Comment by marinarose92** [comment]
> Hi, you are right, can you check the code again, I changed it (but did not tested it)

Thank you so much for getting back to me on this! I used your new code, but it is telling me that $scope is not defined. I did some research on this error, and it mentions something about adding the scope to the controller, but I can't find where the controller is defined? 

Here is my site, if that could help: https://mainlib.org/datepicker/index.php

**Comment by mgohin** [comment]
Are you familiar with AngularJS ? This code must be in the controller of the page

**Comment by marinarose92** [comment]
> Are you familiar with AngularJS ? This code must be in the controller of the page

Hi again, I am so sorry but I am still learning. I believe I figured it out, but the code is still not working for me. https://mainlib.org/datepicker/index.php

It does show multiple calendars, but it still only displays as September, the current month. I am not getting any errors.

**Comment by mgohin** [comment]
Page not found for your link.
You need to add an angular controller on the div that wrap all calendars.
Then you need to create 12 variables pointing to each 12 months you need and use each month on each calendar directive.
I'm sorry I don't have time to do basic AngularJS support.
