### ISSUE TITLE
Selecting Dates

### ISSUE THREAD

**Issue by alanTorresManci** [arca-computing/MultipleDatePicker#66]
im trying to use de multipledate picker, i have an event wich already has dates, how can i automaticlly show them on the callendar, ive allready tried with the ng-model and nothing appears there, when i use the selected-days attribute an error is shown in the console, it says that anngular has made too may loops and crashed

this is my tag
`<multiple-date-picker ng-model="selectedDates"></multiple-date-picker>`

this is where I add data
`
$scope.selectedDates = [];
$scope.selectedDates.push(moment());
`

**Comment by mgohin** [comment]
Hi,

you want to pre-select dates or you want to highlight some dates ?

**Comment by alanTorresManci** [comment]
Im trying to pre select the dates, I`m using an older version, 

> @author : Maelig GOHIN For ARCA-Computing - www.arca-computing.fr
> @date: January 2016
> @version: 1.4.1

i read that i can use "daysSelected", and it works, but for some reason an error is shown on the console

**Comment by mgohin** [comment]
Can you use the latest version?

**Comment by alanTorresManci** [comment]
let me try

**Comment by alanTorresManci** [comment]
i migrate to the next version, but the same error appears `rootScope:infdig`

**Comment by alanTorresManci** [comment]
TypeError: daysSelected.map is not a function

**Comment by mgohin** [comment]
Can you give me here your html and js code? 
It's really difficult to help you without it

**Comment by alanTorresManci** [comment]
this is the implemented directive
`<multiple-date-picker selected-days="selectedDates" ng-model="selectedDates"></multiple-date-picker>`

the js scope is `$scope.selectedDates = [moment()];`

**Comment by mgohin** [comment]
Ok, now you have the latest version, don't use `selected-days` use `ng-model` only

**Comment by jumph4x** [comment]
Also experiencing this. It is Sunday here now and it just became a huge issue suddenly. 

In my case using only ```<multiple-date-picker />``` is enough to cause the error. No attributes, no nothing. 

Moment 2.14. MDP 2.0.7.

**Comment by jumph4x** [comment]
The infdig seems to be happening when line 138 is evaluated, which is this part of the tempalte:

```
<div class="text-center picker-day {{getDayClasses(day)}}" title="{{day.title}}" ng-repeat="day in days" ng-click="toggleDay($event, day)" ng-mouseover="hoverDay($event, day)" ng-mouseleave="dayHover($event, day)">{{day ? day.mdp.otherMonth && !showDaysOfSurroundingMonths ? \'&nbsp;\' : day.date.format(\'D\') : \'\'}}</div>
```

**Comment by mgohin** [comment]
Could you provide me an example like on jsfiddle ?

**Comment by jumph4x** [comment]
@mgohin Take a look here, one external CSS file links to our production file:

https://jsfiddle.net/jumph4x/0zc1q3sj/2/

**Comment by jumph4x** [comment]
Here is one with the main JS file broken apart and separate dependencies:

https://jsfiddle.net/jumph4x/exsLngbh/1/

**Comment by jumph4x** [comment]
And having done all that, it seems that going from ```AngularJS v1.3.0-beta.11``` to ```AngularJS v1.3.0``` solves the problem. 

:)

**Comment by mgohin** [comment]
So no more problem ? :)
