### ISSUE TITLE
Selected dates only showing after I click a date

### ISSUE THREAD

**Issue by mick1313** [arca-computing/MultipleDatePicker#67]
Here is my situation I have a 5 months on the page, and each points to the same array of selected dates (coming from the DB, ones that have already been selcted).  But the Calendar shows up normal, nothing is selected.  I also have the weekends set to off.  If I select a date, all of the dates in the array display properly and then the weekend dates turn off....  but I would think they should start that way.  Here is my relevant code...

    <multiple-date-picker month="item"
                          week-days-off="[0, 6]"
                          disallow-back-past-months="true"
                          disallow-go-futur-months="true"
                          ng-model="mmc.selectedDates"
                          sunday-first-day="true">
    </multiple-date-picker>

item is the first day of the month, this block is a repeater for X number of months.  In my code, the dates are selected, we show the months and populate the dates like this...

        this.selectedDates = new Array<moment.Moment>();
        for (var x of this.menuAssign.SpecificDates) {
            this.selectedDates.push(moment(x));
        }

It is correctly populated.  The calender displays blank, lets say I have 4 dates in the selected array.  If I select any other date.. those 4 automatically show up as selected, and the weekends turn off.. but it should display that way on first display....

**Comment by mgohin** [comment]
If I try your piece of code on my demo page, it's working well.
Can you provide a working jsfiddle showing your problem ?
Are you using a angular beta version ?

**Comment by mgohin** [comment]
Another point, you should use `disableNavigation` instead of `disallowBackPastMonths` and `disallowGoFuturMonths` to disable navigation properly, or you'll be able to navigate in calendars until you are on current month

**Comment by mick1313** [comment]
Actually, I noticed I was 3 or 4 minor versions behind, so I upgraded and that solved the problem.  I noticed it because one of the other issues mentioned the disableNavigation property and I thought.. hmm that's not in my version...  Thanks for the quick response.

**Comment by mgohin** [comment]
You are welcome, we add similar issue this week :)
