### ISSUE TITLE
ng-model for the watch breaks on de-selecting dates

### ISSUE THREAD

**Issue by dovtenenboim** [arca-computing/MultipleDatePicker#68]
When selecting multiple dates there's no issue whatsoever and it works perfectly. The issue I've run in to is when I then deselect a date the watch stops (as I can see by nothing outputting in console) and when I select dates again it the selected values don't output in console.

Seems there's an issue with the deselecting of dates that then caused the next selection to be prevented from registering in the watch? Obviously the expected behaviour is on deselect of a date it removed that date from the array.

```
    $scope.selectedDates = []; 
    //$scope.selectedDates.push(moment());

    $scope.$watch('selectedDates', function(value) {
      console.log('selectedDates', value);
    }, true);
```

angular.js version: 1.5.8
moment version: 2.10.6
moment-timezone.js version: 0.5.5
angular-multiple-date-picker version 2.0.7

**Comment by mgohin** [comment]
Hi,

I don't have this problem on the demo page, could you provide a jsfiddle ?

Thanks :)

**Comment by dovtenenboim** [comment]
@mgohin that's the strange thing, when I added most of the modules as a Plunkr it works. 
I'm using Ionic with it and have added it in to the Plunkr http://plnkr.co/edit/KUnTayUGjzxpi0yryJKF?p=preview. 
Do you have any idea what could potentially cause the watch to only work on selecting but not deselecting - maybe you've come across it before?

**Comment by mgohin** [comment]
Sorry I never used Ionic, maybe you can find some leads on stackoverflow ?
http://stackoverflow.com/questions/31844864/angular-js-scope-watch-issue-ionic-framework
http://stackoverflow.com/questions/29127168/scope-watch-in-angular-doesnt-work-in-ionic-cordova

Sorry I can't really help you. If you find anything it would be nice to tell us here, to help people who will come across this problem :)

**Comment by dovtenenboim** [comment]
Thank you, I definitely will once I resolve it :)

**Comment by Chris0lsen** [comment]
@dovtenenboim I thought I had a similar issue, but felt pretty foolish once I saw my error.

I updated from an earlier version of multiple-date-picker, and the path in my bower_components directory changed from multiple-date-picker/ to angular-multiple-date-picker/, but my browserify was still looking in the old directory... Not sure if your Ionic project is using browserify or webpack or something similar, but if you're upgrading from an older version and using bower, it might be something to look in to.

**Comment by mgohin** [comment]
I added it to npm later than bower, that's why the name changed, I guess :p

**Comment by Chris0lsen** [comment]
@mgohin No worries, just trying to help :)

I was still having trouble in Angular 1.4.8, so I changed some code in toggleDay() in the directive itself. It shouldn't have made a difference, but it seems to be more stable now. 

```
if (day.mdp.selected) {
  scope.ngModel.push(day.date);
} else {
  /*
  scope.ngModel = scope.ngModel.filter(function (date) {
    return !day.date.isSame(date, 'day');
  });
*/
  var idx = -1;
  for (var i = 0; i < scope.ngModel.length; ++i){
    if (scope.ngModel[i].isSame(day.date)){ 
      idx = i;
      break;
    }
  } 
  if(idx !== -1) scope.ngModel.splice(idx,1);
} 
```

**Comment by mgohin** [comment]
Hmmmm, so it works better @dovtenenboim with @Chris0lsen changes ? 
If so I'll update the lib :)

**Comment by mgohin** [comment]
Ok, give me some minutes, I'll update the lib ! 
Thanks @Chris0lsen for the tip !

**Comment by mgohin** [comment]
2.0.8 available, let me know :)

**Comment by dovtenenboim** [comment]
Thanks @mgohin and @Chris0lsen
