### ISSUE TITLE
Dynamically updating disable-days-before and disable-days-after

### ISSUE THREAD

**Issue by dovtenenboim** [arca-computing/MultipleDatePicker#71]
@mgohin Just a heads up that there is no watch for these two which I was surprised to find. Please update the library to include a watch for these in scope.

```
scope.$watch('disableDaysBefore', function () {
    scope.generate();
}, true);

scope.$watch('disableDaysAfter', function () {
    scope.generate();
}, true);
```

**Comment by mgohin** [comment]
All variables are not watched.
Done in 2.0.11 :)
