### ISSUE TITLE
Add support for ng-required

### ISSUE THREAD

**Issue by Jean-Rashmir** [arca-computing/MultipleDatePicker#72]
When the multiple-date-picker is **used inside a form**, support for the **ng-required attribute** would be great in order to disable the submit button as long as not at least one date is selected.

Maybe support for a mimimal amount of dates that have to be selected would also be interesting - so in order for the submit button to be enabled at least for example 3 dates have to be selected. This could be done for example with **min and max attributes**.

**Comment by mgohin** [comment]
Hi,

you can manually do it by watching the `ng-model`, I'll dev it but not right now, I'm back from holidays and have some work to do ;)

**Comment by mgohin** [comment]
just watch the `ng-model`, I don't want to support `ng-required` because we don't know what you require (1 day selected at least, only ?)
