### ISSUE TITLE
Update versions of angular and moment?

### ISSUE THREAD

**Issue by rohdef** [arca-computing/MultipleDatePicker#74]
Hi, and first off thanks for last that I submitted issues :) It was one of the fastest reactions I have seen in a while :+1: 

Let us see if we can't keep up the nice score on that :) We finally got round to managing project dependencies with bower, and I was super happy to see that you support bower :) But when I install it I get:

    bower not-cached    https://github.com/arca-computing/MultipleDatePicker.git#*
    bower resolve       https://github.com/arca-computing/MultipleDatePicker.git#*
    bower checkout      multiple-date-picker#2.0.12
    bower resolved      https://github.com/arca-computing/MultipleDatePicker.git#2.0.12
    bower not-cached    https://github.com/angular/bower-angular.git#~1.3.1
    bower resolve       https://github.com/angular/bower-angular.git#~1.3.1
    bower not-cached    https://github.com/moment/moment.git#~2.10.2
    bower resolve       https://github.com/moment/moment.git#~2.10.2
    bower checkout      moment#2.10.6
    bower checkout      angular#v1.3.20
    bower resolved      https://github.com/moment/moment.git#2.10.6
    bower cached        https://github.com/moment/moment.git#2.15.1
    bower validate      2.15.1 against https://github.com/moment/moment.git#>= 2.6.0
    bower cached        https://github.com/moment/moment.git#2.15.1
    bower validate      2.15.1 against https://github.com/moment/moment.git#^2.15.1
    bower resolved      https://github.com/angular/bower-angular.git#1.3.20
    bower cached        https://github.com/angular/bower-angular.git#1.5.8
    bower validate      1.5.8 against https://github.com/angular/bower-angular.git#>=1.4.0
    bower cached        https://github.com/angular/bower-angular.git#1.5.8
    bower validate      1.5.8 against https://github.com/angular/bower-angular.git#^1.5.8
    bower cached        https://github.com/angular/bower-angular.git#1.5.8
    bower validate      1.5.8 against https://github.com/angular/bower-angular.git#>1.2.0
    bower ECONFLICT     Unable to find suitable version for angular

I suspect this is just a matter of giving it a version bump in bower.json, I can see that we're using angular ^1.5.8 and moment ^2.15.0. If I recall right (it's been a while since I looked at the code) there should be no reason why the MultipleDatePicker shouldn't work with those :)

I hope I'm right in that assumption and if so that we could get this :)

**Comment by mgohin** [comment]
Should be ok now with 2.0.13, please check ;)

**Comment by rohdef** [comment]
It seems that it doesn't work, looking at the change log it could look like that bower.json is unchanged. Isn't that the one that bower uses to decide on its dependencies?

**Comment by mgohin** [comment]
Ho my bad, I changed only `package.json`, be right back ;)

**Comment by mgohin** [comment]
2.0.14

I'm not using bower anymore in my projects, so I just forgot to update it.
I keep bower in this project only for people using it with bower.

**Comment by rohdef** [comment]
That happens to all of us :) I find it nice to have a separation of my build/dev tools and frontend dependencies, so I find the separation quite nice :) Thanks a lot mate. My co-dev @juztme just confirmed that it works :)
