### ISSUE TITLE
Setting the time of the day/neutral time zone

### ISSUE THREAD

**Issue by rohdef** [arca-computing/MultipleDatePicker#77]
Hey again :)

It would be nice to specify when on the day new selections are created. Eg., in the system I'm working on all users are expected to (at least currently) be located in the timezone "Europe/Copenhagen", which naturally means that this is what moment is set to. That is, GMT+2. However our server side considers GMT as the neutral time zone, which means that all dates that is sent to the server ends up being the day before the one actually selected.

Thing is the fields are stored in the database using a date, so let us say that I create a date the 22. June 2016, then it will send 2016-06-22T00:00:00+02:00 to the server, which then transforms it to 2016-06-21T22:00:00+00:00 and stores it in the database as a date that is 2016-06-22T00:00:00+02:00. Next time the data is loaded the response I get is 2016-06-21T00:00:00+00:00, which fortunately stays consistent from that time on (as long as I don't mess with other time zones :p )

Currently I post-parse all the fields ensuring a consistent time, but it would be nice to have the option to specify the desired time of the day, or perhaps even better a neutral time zone, to overcome this issue.

**Comment by mgohin** [comment]
I think you'll have to keep post parsing dates, I don't want to add too much dependencies to the date-picker, it's pretty simple to do it with [MomentTimeZone](http://momentjs.com/timezone/docs/)

Moment is giving you an Iso8601 date, so you have everything you need to work with it server-side. If there is a timezone in it (`+02:00`), your client, server and DB should deal with it easily.
