### ISSUE TITLE
prevent change month

### ISSUE THREAD

**Issue by jetta20162** [arca-computing/MultipleDatePicker#78]
Hi,

i need to have something like a monthChange(event) function. I want to prevent the user from changing the month without disable the buttons, similar to dayClick(event,...). Is this somehow possible in the current version?

Thanks & Best Regards,
Thomas

**Comment by mgohin** [comment]
Hi,

it's not possible, there is the `monthChanged` but it does not allow to prevent month to change.
I'll add this today, working the same way as `dayClick` with an event.

**Comment by jetta20162** [comment]
Thank you very much!

**Comment by mgohin** [comment]
Can you check 2.1.0 ? :)

Demo updated : [month-click](http://arca-computing.github.io/MultipleDatePicker/#month-click)

**Comment by jetta20162** [comment]
Thanks, i will check today! :-)

**Comment by jetta20162** [comment]
Everything looks fine, thanks :-)
