### ISSUE TITLE
[Question] Is there a way to disable date selection?

### ISSUE THREAD

**Issue by qunerd** [arca-computing/MultipleDatePicker#79]
Hey there,

great library, I'm using it for setting training dates in admin panel and want also use it to show the dates for the participants. They should not be able to manipulate the data. I've tried some options described in the documentation but it unfortunately doesn't fit my needs. Is there a way to disable selecting/deselectig any date but keep the oryginal looks?

Greetings
Marcin

**Comment by mgohin** [comment]
Hi, 

thanks, glad you use it.

If you cant to disable navigation, you can use `disable-navigation=true`.
For days the magic trick is to use `day-click=disableClick` callback and prevent the event, so nothing will happen and the calendar will remain as it is.

```javascript
    $scope.disableClick = function(event) {
        event.preventDefault();
    }
```

Let me know if it works as expected ;)

**Comment by mgohin** [comment]
Checking for updates, is it working ?

**Comment by qunerd** [comment]
Yes! Works as expected. One thing though: hovering over a day still causes the item to show as selected. Is there also a workaround for that other than tweaking css?

Sorry for asking for features which are clearly not the main goal of the library.

I've also noticed `day-click` is fired not only on clicking but also on hover. Is that by design? Edit: checked and [it seems it is](http://arca-computing.github.io/MultipleDatePicker/#dayclickdayhover). I find it a bit confusing naming.

**Comment by mgohin** [comment]
Ho no, there a `day-click` and a `day-hover` parameter, the demo isn't explicit enough, gonna change it right now ;)

So to prevent the over, just give to `day-hover` the same callback as `day-click` because your callback prevent event, it works for both params.

**Comment by qunerd** [comment]
Unfortunately it didn't work. I've added the callback to `day-hover`, but 
```
event.preventDefault()
```
doesn't do the trick.

**Comment by mgohin** [comment]
Damn you are right.

So the trick is to use css, change the rule 

    .picker-day:not(.picker-off):not(.picker-empty):hover {
        background-color: #C6000B;
        color: #fff;
        cursor: pointer;
    }

for the same as `.picker-day` for exemple

    .picker-day:not(.picker-off):not(.picker-empty):hover {
        background-color: #fff;
        color: #000;
        cursor: default;
    }

**Comment by qunerd** [comment]
Ok that works for me. I had to add `not(.picker-selected)` - otherwise hovering over selected dates would unselect them.

```
.picker-day:not(.picker-off):not(.picker-empty):not(.picker-selected):hover {
    background-color: #fff;
    color: #000;
}
```

The only last thing is the `cursor` changing to `pointer` on selected dates. I've tried several thing to keep in `default` state. No success. This doesn't matter as much I'm already pleased with the result. Thanks for helping me out!

**Comment by mgohin** [comment]
You could add a class surrounding the calendar and redefine a complete path css rule for the over on selected dates so it'll prevent the cursor to show like 

    .surrounding-class .picker-day:not(.picker-off):not(.picker-empty):hover {
        cursor: default;
    }

**Comment by qunerd** [comment]
This works as expected! Thank you so much!

**Comment by mgohin** [comment]
Glad to help.

Do you use it on a public website ?

**Comment by qunerd** [comment]
Not yet. I'll post a link when I'm ready ;)

**Comment by mgohin** [comment]
Thanks, If I can would be nice to add you in the readme, I don't ask often enough :)
