### ISSUE TITLE
is this for angular 2

### ISSUE THREAD

**Issue by xtianus79** [arca-computing/MultipleDatePicker#81]
and or do you have any plans for integration... we really want to use this component

**Comment by mgohin** [comment]
Hi,

it's not for angular 2 right now, maybe it works I don't know.

I don't have planned to release an angular 2 version for 2 reasons : I never used angular 2 yet, I don't have time (pretty busy at work).

I'm sure it's not that hard to migrate, just don't have time to try :(

I accept any PR ;)

**Comment by xtianus79** [comment]
@mgohin lets do it

**Comment by mgohin** [comment]
be my guest ;)

**Comment by xtianus79** [comment]
@mgohin I have create a fork and corresponding npm https://github.com/xtianus79/multiple-date-picker-a2 ... so far i have upgraded a couple things such as angular 2 dependencies... today I will be experimenting on how we can fit it in.  i will post some articles here but my angular 2 knowledge is much larger than my angular 1 knowledge so this should could be challenging.

**Comment by mgohin** [comment]
Ok, keep me in touch, when it properly works I'll add a link to your repo in the readme ;)

**Comment by xtianus79** [comment]
@mgohin I have created an angular 2 via system.js (instead of webpack at this point) sandbox... https://github.com/xtianus79/angular2-multiple-date-picker-a2  I am going through syntax typescript things at the moment.

One question I have currently is the use of ngModel.  I am thinking of doing something similar but wanted to hear your thoughts on it and what your idea behind it was.  formcontrol isn't in the html.

**Comment by xtianus79** [comment]
@mgohin hey made really great progress today in the sandbox ad I am posting that now.  once I full 'modularize' it i will have it as a working download in npm...

**Comment by mgohin** [comment]
Nice. I don't have any thoughts on Angular 2, never played with it :/

**Comment by xtianus79** [comment]
Hi @mgohin I have most everything working and this is production ready as we are using it... I have added a couple features too that I might spell out further in future builds such as options for <md-icon> or <font-awesome> icons as the left and right caret instead of the text only option.  little things like that. 
https://github.com/xtianus79/multiple-date-picker-a2

I really need to update the documentation though.... but it is shippable if you would like to link to it or provide 

thanks for starting this and thanks for your help.

**Comment by mgohin** [comment]
Ok nice 👍 
I'll link it when you updated some doc, at least the readme with basic instructions to guide users.

**Comment by mgohin** [comment]
@xtianus79 can you please add 'Issues' to your repo to let people open tickets for A2 version ?
And can you update package.json, bower.json (etc) files with your infos ?

Thanks ;)

**Comment by xtianus79** [comment]
Yes... Sorry about that I didn't realize it wasn't open

**Comment by mgohin** [comment]
No prob ;)

**Comment by xtianus79** [comment]
@mgohin just to let you know i have update documentation... thanks for the help
