### ISSUE TITLE
custom select

### ISSUE THREAD

**Issue by RawiaAhmed** [arca-computing/MultipleDatePicker#82]
I'm using the picker it's really very nice, simple and helpful.
I want to know if there is a way that I can select a year or a month all at once without selecting day by day

**Comment by mgohin** [comment]
Hi,

thanks, glad you like it.

You want to pre-select a year or month before the user select a date ?

**Comment by RawiaAhmed** [comment]
I'm having an option that the user can select all days or all month, I wonder if there is a way to do this without having to loop over the whole year or month

**Comment by RawiaAhmed** [comment]
I thought so, unfortunately I'll have to do it all by my self, thanks a lot for the suggested library I'll try to use it.

**Comment by mgohin** [comment]
Let me know if you need help to achieve it ;)

**Comment by mgohin** [comment]
Did you manage to do it ?

**Comment by RawiaAhmed** [comment]
yes I did it the old fashion way, for loop through all the days searching for the ones I need, Thanks alot :)
