### ISSUE TITLE
Rendering multipledatepickers on single page slows down the application .

### ISSUE THREAD

**Issue by docodon** [arca-computing/MultipleDatePicker#83]
I am using this plugin and it is really awsome . 

But when I use multiple datepickers on a single page following this [issue](https://github.com/arca-computing/MultipleDatePicker/issues/65) . 
The page rendering in anugular app gets really slow particularly when quite a number of dates have been picked.

You can see the issue faced be me over here as well 
[my heroku app](https://secure-atoll-63871.herokuapp.com/#!/) . 

Any sort of help is appreciated.

**Comment by mgohin** [comment]
I guess you use the same ng-model on every calendars, can you try to use a different ng-model on each calendar ? Just to test performances

**Comment by mgohin** [comment]
Any news ?

**Comment by docodon** [comment]
hey ! apologies for being that late :\
What I tried is instead of 12 shown 4 on each page or 3 on each page , it makes the things quite fast.
And  one more things which I was doing is disabling the click on dates on a page where 12 months were being rendered 

So to prevent the click from happening i tried this 
https://github.com/arca-computing/MultipleDatePicker/issues/79
`
$scope.disableClick = function(event) {
        event.preventDefault();
  }
 `

It made the hovering on the page really slow .

For this a css solution which I propose is : 

`pointer-events:none`

Currently there are no trouble , so closing the issue for now .
