### ISSUE TITLE
Can I detect user select date not continue? 

### ISSUE THREAD

**Issue by avatarr** [arca-computing/MultipleDatePicker#85]
I want to force user to select continuous date. For example
<img width="1006" alt="screen shot 2560-02-27 at 1 10 20 am" src="https://cloud.githubusercontent.com/assets/1640817/23342257/9ba4c91e-fc89-11e6-9152-bd1c9e0d8e7f.png">
In a image I start at 4 in a normal flow user should select 11 but if user select 18 I want to warn them and unselect, In the other case if user select 4 then 11 and 25 a system will detect and warn them and unselect because user have to select 18 

any suggestion? 
Thanks in advance.

Ps. I very love this lib easy to use and many option to use. Love this.

**Comment by mgohin** [comment]
> Ps. I very love this lib easy to use and many option to use. Love this.

Thanks, I'm always glad to see people enjoying this lib ;)

So there is a very nice option : `dayclick`. You give it a scope callback and can prevent selection to happen (it'll not select then unselect, it'll prevent selection to happen, so nothing will be triggered if you have some $watch or callbacks).

For example, in html

    <multiple-date-picker day-click="checkSelection"></multiple-date-picker>

in your controller

    $scope.checkSelection = function(event, date) {
        if(!canBeSelected(date)){
            event.preventDefault();
            alert('Sorry bro, you can\'t select this date');
        }
    }

Does it answer your question ?

**Comment by avatarr** [comment]
@mgohin This way is very simple. Thank you for your answer and I implemented it's work for me.

I will close this issues
