### ISSUE TITLE
How to get the date in certain format

### ISSUE THREAD

**Issue by PickHoon** [arca-computing/MultipleDatePicker#86]
Hi, I would like to ask how can I get the date selected in specific format?
The below image shown what I got at the moment.

SearchCtrl.prototype.oneDaySelectionOnly = function (event, date) {
    this.btndtbegin=this.selectedDays;
    //this.selectedDays.length = 0;
};

Any help will be appreaciated!

![capture](https://cloud.githubusercontent.com/assets/17921805/23625955/100203d2-02e6-11e7-9d96-83d50b0aa2c7.PNG)

**Comment by mgohin** [comment]
Hi,

very simple, because I use momentjs, you can use [.format()](http://momentjs.com/docs/#/displaying/format/)

`this.btndtbegin = this.selectedDays.format('YYYY-MM-dd')`

I suggest you to use the date given as a param instead of setting btndtbegin with selectedDays that is an array ;)
