### ISSUE TITLE
HighlightDays is Working

### ISSUE THREAD

**Issue by lalitdograldh** [arca-computing/MultipleDatePicker#87]
Please change your code of to if ((_this.highlightDays === Array)) to 
if ((typeof _this.highlightDays === "object")) and this will solved HightlightDays problem in multiple-date-picker-a2 and please upload component.js file as soon as possible and we are using this package of multiple-date-picker-a2(multiple-date-picker-a2@2.5.3).

**Comment by mgohin** [comment]
Hi,

please open a ticket on the github repo of the Angular2 version right here : https://github.com/xtianus79/multiple-date-picker-a2
I'm not the one handling this version ;)

**Comment by mgohin** [comment]
I asked him to add 'Issues' options to his repo in #81

**Comment by xtianus79** [comment]
Hi @lalitdograldh you can come over to my branch I will update this for you and test it out.  I don't think i fully tested that section.  see you here

https://github.com/xtianus79/multiple-date-picker-a2

**Comment by xtianus79** [comment]
@lalitdograldh just to let you know I fixed the issue and tested it out and have it working.  going to be working on documentation and readme tonight.  I need to make a couple more updates prior to the next release.
