### ISSUE TITLE
Cannot read property 'isSame' at toggleDay

### ISSUE THREAD

**Issue by Simsal** [arca-computing/MultipleDatePicker#88]
Hey,

i want to use the MultipleDatePicker on a website where teams can deselect non-working days.

Per month in a project there will be a new multipledatepicker. And this for each team. I'm using it like the following:
```
<div class="col-md-6" ng-repeat="month in months">
                <multiple-date-picker month="month" ng-model="team.allWorkingDays" disable-navigation="true"></multiple-date-picker>
</div> 
```  

My array of Dates is like the following:
0:"2017-02-14T00:00:00+01:00"
1:"2017-02-15T00:00:00+01:00"
2:"2017-02-16T00:00:00+01:00"
3:"2017-02-17T00:00:00+01:00"
4:"2017-02-18T00:00:00+01:00"

If i now click on a allready selected day, i get the following error:

TypeError: Cannot read property 'isSame' of undefined
    at ChildScope.scope.toggleDay (multipleDatePicker.js:311)

The date gets visually deselected, but the model doesn't get updated. Any idea about this?

Greetings

**Comment by mgohin** [comment]
Hi,

are you using momentJs dates in the array of dates ?

**Comment by Simsal** [comment]
Hey,

oh god. Simple Question already solved the problem. I formatted all my momentJs dates with the .format() function. I didn't use the full date object.

After changing it it is working as expected.

Thank you for the advice and the MultipleDatePicker!
