### ISSUE TITLE
Optional parameters in dayClick for identifying source in ng-repeat

### ISSUE THREAD

**Issue by Simsal** [arca-computing/MultipleDatePicker#89]
Hey,

and my next issue ;)

as mentioned in #88 i have some datepickers for each registered team, working on the same project.
```
<div class="row" ng-repeat="team in teams">            
            <div ng-repeat="month in months">
                <multiple-date-picker month="month" ng-model="team.allWorkingDays" disable-navigation="true"></multiple-date-picker>
            </div>            
</div>
```  

i'd like to identify in which team the day got selected/unselected. Normally i do this by adding a parameter to the ng-click function. As i understand your code this is not possible. Any idea how to achieve this?

Greetings

**Comment by mgohin** [comment]
Hi again ;)

Can you check what is in the first param `event` ? Nothing to help you out ?
I think you can get the clicked element, so its parents, so an id ?

ex : 

    <div class="row" id="team-{{team.id}}" ng-repeat="team in teams">...</div>

**Comment by Simsal** [comment]
Thank you for the advice.

I can get the id by traversing the path to the clicked element.

It is definitely not the cleanest solution, but nevertheless, it works.

Thank you for your assistance and have a nice sunny Sunday ;)

**Comment by mgohin** [comment]
Thanks.

It's not the best solution but I remember an option I used to set an id to the picker but it didn't work well (probably my bad).

Have a nice sunday under the rain too :D (It is here in Bordeaux, France)
