### ISSUE TITLE
Selecting and De-selecting Dates. Help Needed

### ISSUE THREAD

**Issue by arjunajithtp** [arca-computing/MultipleDatePicker#92]
Hi, I am using MultipleDatePicker in Ionic. The ng-model is not getting updated with the selection and deselection of dates. 

          $scope.calendar = {};

          $scope.activeDate = new Date();
          $scope.selectedDates = [];

          $scope.calendar.myArrayOfDates = [moment().date(4)];

          $scope.$watch('calendar.myArrayOfDates', function(newValue, oldValue){
              if(newValue){
                  console.log('my array changed, new size : ' + newValue.length);
              }
          }, true);

          <multiple-date-picker ng-model="calendar.myArrayOfDates"  sunday-first-day="true"></multiple-date-picker>

Even the initial values in `$scope.calendar.myArrayOfDates` is not selected in the view. Please help me.

**Comment by mgohin** [comment]
Hi,

I never used it in Ionic :/

I suggest to use the non minified js and debug it to check what happens in the generate function (is the $scope.ngModel set with your values ?).

**Comment by arjunajithtp** [comment]
@mgohin Thanks for the quick reply. I checked as you suggested. My values are **not received** in `scope.ngModel`

**Comment by mgohin** [comment]
Is `sunday-first-day` true when you debug inside or it's false (value not set too) ?

**Comment by mgohin** [comment]
Check this playground : http://play.ionic.io/app/4a550bb615ee

Looks like you have to use scope variable names as they are defined in the directive. So try with 

```  <multiple-date-picker ngModel="calendar.myArrayOfDates"  sundayFirstDay="true"></multiple-date-picker>```

**Comment by arjunajithtp** [comment]
@mgohin `sunday-first-day` is true

**Comment by arjunajithtp** [comment]
`<multiple-date-picker ngModel="calendar.myArrayOfDates" sundayFirstDay="true"></multiple-date-picker>` not working.

**Comment by mgohin** [comment]
can you try to add your dates in a variable in the root of $scope ?

```$scope.myArrayOfDates = [moment().date(4)];

 <multiple-date-picker ng-model="myArrayOfDates"  sunday-first-day="true"></multiple-date-picker>```

**Comment by arjunajithtp** [comment]
Tried it too. :(

**Comment by mgohin** [comment]
Can you provide an example in Ionic's playground ?

**Comment by mgohin** [comment]
any news ?
