### ISSUE TITLE
Set Start Date

### ISSUE THREAD

**Issue by chaturanga836** [arca-computing/MultipleDatePicker#93]
This module is so fantastic, the module has option for disabling dates further and back, but  how to set the start date. of the calendar,  when i disabled the further date, calendar not automatically navigate to the first available month.

**Comment by mgohin** [comment]
Hi
thanks, I'm always glad to see people enjoying the calendar ;)

The [disable-days-before](http://arca-computing.github.io/MultipleDatePicker/#disable-days-before) does not navigate the calendar to the first available date but it's pretty simple, here is an example (not tested) :

```javascript
$scope.disableBefore = moment().add(1, 'MONTH');
$scope.month = moment($scope.disableBefore); //copy
```

```html
<multiple-date-picker disable-days-before="disableBefore" month="month"></multiple-date-picker>
```

**Comment by mgohin** [comment]
any updates ?
