### ISSUE TITLE
Day click does not work with angular service call

### ISSUE THREAD

**Issue by sbkohel** [arca-computing/MultipleDatePicker#96]
When making a function for a click event with just a simple boolean check like below it works as expected.
~~~~
        $scope.checkSelection = function(event, obj) {
                var now = new Date();

                if(($scope.interventionDates.length >= ($scope.interventionDefObj.length * $scope.interventionDefObj.meetings)) && (!containsDate(obj.date) || moment(now).isAfter(obj.date))) {
                  //TODO add conditional check if date has attendance associated with it

                    event.preventDefault();
                }
            };
~~~~
If I add an angular service call like below, even though if the variable resolves to true, and event.preventDefault() fires, the calendar still (un)selects the cell, and the date is added to the model.

~~~~
         $scope.checkSelection = function(event, obj) {               
                var scheduleDate = {};
                scheduleDate.interventionUuid = $scope.intervention.interventionUuid;
                scheduleDate.meetingDate = obj.date._d;
                
                    InterventionCalendar.getUsages($scope.intervention.interventionUuid, scheduleDate).then(function (response) {
                        var isUsed = response.data;

                        if( isUsed) {
                            event.preventDefault();
                            console.log('prevented');
                        }
                        
                    });
                
            };
~~~~

**Comment by mgohin** [comment]
Hi,

it's a normal behavior because your are trying to prevent in a promise, so after the onClick happened.

I suggest your prevent the event, then you make your call, and if the server answer is ok, you add the date to the ng-model.

Here a (not tested) example :

    $scope.allMyDates = ...; //has been init and used for ng-model
    $scope.checkSelection = function(event, obj) {
        var scheduleDate = {}; 
        scheduleDate.interventionUuid = $scope.intervention.interventionUuid;
        scheduleDate.meetingDate = obj.date._d;
        event.preventDefault();
        InterventionCalendar.getUsages($scope.intervention.interventionUuid, scheduleDate).then(function (response) {
            var isUsed = response.data;
            if(!isUsed) {
                allMyDates.push(obj.date);
            }                  
        });            
    };


Let me know if it works ;)

**Comment by sbkohel** [comment]
My use case is if the date was initially selected, I need to check if the id of the date is used as a foreign key on another table and can not be deleted.  I applied your logic above to a case of removing the date from the model, and I was able to get it to work.  Thanks for your help!!!
