### ISSUE TITLE
Remove The Red Background Color Directly

### ISSUE THREAD

**Issue by sky3913** [arca-computing/MultipleDatePicker#97]
How to remove the red background color directly when we click it or when we unselect the day without move the mouse to another day?
Thanks

**Comment by mgohin** [comment]
The red background is when the day is selected.
I'm not sure what you want to do, you never want it to be red or you want to unselect a day ?

**Comment by sky3913** [comment]
I mean, for example you have clicked 11 May 2017, so the 11 May 2017 will be in red background color, and if you click it once again the red background color not removed immediately, you have to move the cursor to another day to reflect the changes.

**Comment by mgohin** [comment]
Ho, it's the hover in css, you can change the color to avoid confusion ;)

**Comment by sky3913** [comment]
I think it's not the hover in css, back to example, if you unselect the 11 May 2017, I want the red background color removed, without move the cursor to another day (still in 11 May)

**Comment by mgohin** [comment]
It is the hover that is same color as when selected, try to change it you'll see.
You can provider an example (fiddlejs) to see the problem

**Comment by sky3913** [comment]
I've change the hover background color 
`hover{background-color:#C6000B;color:#fff;cursor:pointer}`
into
`hover{background-color:#0000FF;color:#fff;cursor:pointer}`
it still doesn't solve the problem.

Ok, try to make it clear, if you unselect the day I want to the background color in white.
Try to click the same day more than one, you can't see the result whether you select or unselect it because the color is same (you will know the result if you move away the cursor from that day).

**Comment by mgohin** [comment]
Here is what you need to change :

```.picker-day:not(.picker-off):not(.picker-empty):hover {
    background-color: #C6000B;
    color: #fff;
    cursor: pointer;
}```

into 

```.picker-day:not(.picker-off):not(.picker-empty):hover {
    background-color: #fff;
    color: #fff;
    cursor: pointer;
}```

**Comment by sky3913** [comment]
Hi...sorry for late reply

It's the same as I do but just different color. I create [jsfiddle ](https://jsfiddle.net/ocyjzjo1/) using bootstrap-datepicker which can select multiple date.

In the jsfiddle, if you for example, click the 11 May 2017 then it will be in blue and if you click it once again, then it will be in red. In your calendar, I have to move the cursor outside 11 May 2017 to see the changes (from red to white)

It's not a big issue, but nice to have.

**Comment by mgohin** [comment]
Ok.

you have to change the css rule for 

    .picker-day:not(.picker-off):not(.picker-empty):not(.picker-selected):hover

So the hover will not apply when day is selected

**Comment by sky3913** [comment]
Still the same.

Here is the [plunker](https://plnkr.co/edit/4C9B3LVr7z2C3GTCLd2h?p=preview) to show it the changes.

**Comment by mgohin** [comment]
Add this at the end of multipleDatePicker.css and it works.

    .picker-day:not(.picker-off):not(.picker-empty):not(.picker-selected):hover {
         background-color: #456780;
    }

**Comment by sky3913** [comment]
Ok it works, thanks @mgohin
