### ISSUE TITLE
How to set month navigation dynamically

### ISSUE THREAD

**Issue by sky3913** [arca-computing/MultipleDatePicker#98]
I add a dropdown that contains list of years. If I select for example 2018 then the month navigation should start from 1 januari 2018 to 31 december 2018.

I can do this by using `month-click="vm.setMonthRange"` in html and then in javascript:

```
setMonthRange(event, month) {
        if (month.isBefore(moment().startOf('year')) || month.isAfter(moment().endOf('year'))) {
            event.preventDefault();
        }
    }
```

Is there any a way how to set the month navigation dynamically based on the selected year in the dropdown?

**Comment by mgohin** [comment]
You can use http://arca-computing.github.io/MultipleDatePicker/#disallow-back-past-months and http://arca-computing.github.io/MultipleDatePicker/#disallow-go-futur-months
Set dynamically a variable of your scope when the month change. If it's January then set disallow-back-past-months to true, if it's December the set disallow-go-futur-months to true

**Comment by sky3913** [comment]
Ok I'll give it a try, thanks
