### ISSUE TITLE
Parse selectedDays to jquery variable

### ISSUE THREAD

**Issue by Robstaer** [arca-computing/MultipleDatePicker#99]
Hello and thanks for your wonderful work!

I'm struggeling with an issue i'm not able to resolve for a few days now, that's why i'm asking here directly:

How can i access {{pickedDays}} directly and asign a variable in jquery to it?

http://stackoverflow.com/questions/43897324/multiple-date-picker-to-jquery-variable

Here i asked on stackoverflow, without a solution...

Something like:

var arrayDates = [];
arrayDates = {{pickedDays}};

Do you have any ideas?

Thanks in advance!

**Comment by mgohin** [comment]
Hi,

why do you want to do it ? 
You should code the conversion in the angular controller, from `$scope.pickedDays` to your jquery variable `arrayDates`.

I'm not sure to understand what you want to achieve.

**Comment by Robstaer** [comment]
http://lernplan.bplaced.net/

Here is an example, the code is:

> <body ng-controller="demoController">
> <div>
>     <multiple-date-picker ng-model="pickedDays"></multiple-date-picker>
> </div>
> <div>
>     <h1>{{pickedDays.length}}</h1>
>     <h2><pre>{{pickedDays | json}}</pre></h2>
> </div>
> 
> <div>
>     <p onclick="myFunction()">Get ng-model variable...</p>
>     <script type="text/javascript">
>     function myFunction() {
>         alert("Next alert will show the assigned pickedDays to an jquery variable, if it works...");
>         alert($scope.pickedDays)
>         }
>     </script>
> </div>

**Comment by mgohin** [comment]
Why doing this in Jquery ???

Just do it in your `demoController`

change in your html 

    <p ng-click="myFunction()">Get ng-model variable...</p>

add in your controller

    $scope.myFunction = function(){
        alert($scope.pickedDays)
    };

**Comment by Robstaer** [comment]
Because i want to create a calendar with ical events using ical.js and data from a postgreSQL database. In order to use the ical.js, the "free days" would need to be parsed from angularjs "{{pickedDays}}" to a jquery variable var array = ["freeday1", "freeday2", ...].. i managed to get your example to work, but the alert was just a test to see if the parsing to a jquery variable works - with your workaround, i'm simply parsing the angularjs variable to the alert window!

**Comment by mgohin** [comment]
What you do in jquery, you can simply do it too in your controller inside the `myFunction()` function

**Comment by Robstaer** [comment]
Really?
So i can access my database (PostgreSQL) using php and parse the table to angular as well? All inside the myFunction() function?

**Comment by mgohin** [comment]
With JS you should use REST Services.

So on server side, you create a WS giving you data you want and call this WS with `$http.get` inside your controller.

If you are using angular and if you don't use Jquery plugins, you should not use Jquery ;)

**Comment by Robstaer** [comment]
I managed to import all files needed, but i can't find a solution to create a simple .ics file with multiple events (on the selected days in the multiple date ipcker) with angular, which can be downloaded and directly imported to your iphone calendar.. Do you have an idea?

Thanks a lot for your help, as i'm struggeling to find solutions online for the relatively new angular..

**Comment by mgohin** [comment]
Why don't you create the `.ics` file server side ? I guess it easier ?

**Comment by Robstaer** [comment]
Could you give an example? I need to parse the angular variables of the multiple date picker to the backend, for example php right? Or what are you referring to specifically when you mean server side? node.js? My webserver (bplaced) only supports php, postgresql and mysql, no node.js..

**Comment by mgohin** [comment]
I can't help you for php development.
Ho do you do with jquery to generate your file ?

**Comment by Robstaer** [comment]
i managed to create a string with the ical-event-strings.
var x = eventstring
How can i easily download a file containing the string x as a calendar.ics file? I don't want the 'save as' function there, just a direct download - do you know how?

**Comment by mgohin** [comment]
http://alferov.github.io/angular-file-saver/
